### ISSUE TITLE
Custom Attributes

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#100]
Often, stores may want to store additional information about customers, orders or products for things like delivery notes or IDs to match things up in external services.

Right now with Simple Commerce this just isn't possible but I'm proposing a way to make it work:

The developer would have to add the custom attribute fields they want to the Blueprint of the resource and they would have to add it to a configuration file:

```php
<?php

return [
      'fields' => [
           'products' => ['printful_id'],
      ],
];
```

In the code of addon, all we would have to do is look for any of those custom fields specified in the configuration in any Control Panel publish form requests or the checkout request and we would store that information in a `custom_fields` column in the resource tables.

Respectively, we would treat those fields as any other field when being used in front-end templating.

I know it's a bit complicated but it's something that generally required by lots of e-commerce stores.

**Comment by ryangjchandler** [comment]
Is it scalable enough to store everything in a single column? Presumably it'll be stored as JSON in a text or json column, resources with a large amount of custom attributes might notice some performance issues. 

Why not introduce a new table that has a polymorphic relationship to the resource, and stores it using a key column and value column. Would also let developers add their own columns to the custom attributes, for example, toggling them.

**Comment by duncanmcclean** [comment]
To be honest, I haven't thought much about the scalability of this. 

I see how having everything in one database column would not be the best idea.

I think the table that has the custom attributes would be a better idea. Ideally, those attributes could also be configured through the add-on settings somehow.
