### ISSUE TITLE
🐛Shouldn't all `uid` columns be named `uuid`to be true to the method that fills them

### ISSUE THREAD

**Issue by ryangjchandler** [duncanmcclean/simple-commerce#135]
Not really a bug, not really a feature request just more of a suggestion.

**Comment by duncanmcclean** [comment]
Yeah, they should be, feel free to pr it in.

**Comment by ryangjchandler** [comment]
Have submitted a PR as seen above for this.

**Comment by duncanmcclean** [comment]
Closed by #136
