### ISSUE TITLE
Partial Refunds

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#145]
If someone changes the price of an order, the customer should be given a partial refund from Stripe.

Another option could be to set the order total to being read only which might make more sense.

**Comment by ryangjchandler** [comment]
Probably best to make the total read-only and generate it from the products on the order. If a store manager removes an item from the order, or marks an item as returned, then a refund should be processed if payment has already successfully been taken.

**Comment by duncanmcclean** [comment]
> Probably best to make the total read-only and generate it from the products on the order. If a store manager removes an item from the order, or marks an item as returned, then a refund should be processed if payment has already successfully been taken.

Yes, I agree. Just need to implement this inside the order items fieldtype that displays the products inside the Orders pages in the Control Panel.
