### ISSUE TITLE
Multi-lingual & Multi-site support

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#148]
### Description
I think it would be a good idea for Simple Commerce to work for multi-lingual sites and sites that use the multi-site functionality.

**Comment by plompd** [comment]
+1
Add multi currency too ;)

**Comment by duncanmcclean** [comment]
> +1
> Add multi currency too ;)

#149 Yep, it's on my list.

**Comment by duncanmcclean** [comment]
Currently rewriting the addon with flat files and each multi-site in Statamic will allow for a different set of products/orders, as well as its own currency.
