### ISSUE TITLE
Reporting notifications

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#150]
### Description
I think it would be a good feature for Simple Commerce to send back office statistics as notifications. Kind of like what Baremetrics does for my Saas app.

![image](https://user-images.githubusercontent.com/19637309/74450019-5ad0e080-4e75-11ea-93b7-5bb8a2091fdc.png)

**Comment by ryangjchandler** [comment]
I agree, this is definitely something one of my clients would ask for. Possibly sent in the form of an email, with a configurable recurring period, maybe by default every week?

**Comment by duncanmcclean** [comment]
> I agree, this is definitely something one of my clients would ask for. Possibly sent in the form of an email, with a configurable recurring period, maybe by default every week?

Yeah, that's exactly what I was thinking.
