### ISSUE TITLE
[Feature Request] Control Panel Reports

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#151]
### Description
Simple Commerce should provide reporting to the user so they can view things like recent sales figures, number of new customers and how many variants are nearly out of stock.

**Comment by ryangjchandler** [comment]
This is probably the one thing that is stopping me from using SC at the moment, many clients need this functionality.

**Comment by duncanmcclean** [comment]
> This is probably the one thing that is stopping me from using SC at the moment, many clients need this functionality.

It's planned in the next release. What sort of reports do you think would be useful?

**Comment by damcclean** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Better Reporting](https://trello.com/c/7YAtHfmd/2-better-reporting)

**Comment by ryangjchandler** [comment]
Sales figures are a definite, but it would also be good to have some CSV reports for orders too, so you can see the cost, and maybe even break it down further to each line item, the stock before and after.

**Comment by ryangjchandler** [comment]
Happy to be a test-dummy too!

**Comment by duncanmcclean** [comment]
Hmm okay... might need to talk to you more about this at some point. Planning on building it out in the next few weeks.

**Comment by duncanmcclean** [comment]
Just to provide an update on this issue for v2.1. 

I've partially built out this card as a widget that provides sales information in the Control Panel about the last 7, 14 and 30 days.

I know you wanted CSV exporting ability which sadly won't be coming in v2.1 but I've added it to my roadmap to ensure it's not forgotten about.

**Comment by duncanmcclean** [comment]
This feature has been implemented in v2.1 which I'm hoping to release at some point in the next two weeks. I'm closing this card for now to clean up Github issues. I'll update this card once the update has been released.

**Comment by duncanmcclean** [comment]
Hey Ryan (and anyone else interested)! 

As promised, here's my update to the issue. [v2.1 has been released](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.1.0) and with it comes a little sales widget.

I've added your other reporting features to my secret product roadmap and I'll explore them for further releases. Enjoy!

**Comment by ryangjchandler** [comment]
Secret product roadmap ;)
