### ISSUE TITLE
Support customers having their own accounts

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#152]
### Description
On most e-commerce stores, customers are asked to create their own accounts where they can view the status of orders, their billing information etc. We should do the same thing in Simple Commerce.

**Comment by ryangjchandler** [comment]
What sort of steps are needed for this one? Is there a clear relationship from the customer to the orders already, if so, then the only next step would be linking the user to the customer and having the correct relationships.

**Comment by duncanmcclean** [comment]
It would require building a front-end for it, relationship of a customer and a Statamic user.
