### ISSUE TITLE
Make sure variants get removed in database if they are removed in Control Panel

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#163]
### Description
@ryangjchandler I wonder if we could do a similar thing that we did with the variant attributes where we do a check thing.

**Comment by ryangjchandler** [comment]
Are they not getting removed currently?

**Comment by duncanmcclean** [comment]
I can't remember... I'll check in a bit.

**Comment by ryangjchandler** [comment]
I'll run a quick test now.

**Comment by ryangjchandler** [comment]
> I'll run a quick test now.

They're not getting removed at the moment.

**Comment by duncanmcclean** [comment]
Yeah, that's what I though. I'm guessing the code would be similar to what we implemented for deleting variant attributes?

**Comment by ryangjchandler** [comment]
> Yeah, that's what I though. I'm guessing the code would be similar to what we implemented for deleting variant attributes?

Yeah exactly. If not identical, I'll put this into a PR for you now 😁

**Comment by duncanmcclean** [comment]
> > Yeah, that's what I though. I'm guessing the code would be similar to what we implemented for deleting variant attributes?
> 
> Yeah exactly. If not identical, I'll put this into a PR for you now 😁

Thanks Ryan. Appreciate it!

**Comment by ryangjchandler** [comment]
Just another thing here, shouldn't the SKU numbers be unique for each variant too, since the SKU determines which product has been taken from stock?

**Comment by duncanmcclean** [comment]
Yes, they should be. I'll make that into another issue and I'll work on it after I'm done on product attributes.

**Comment by ryangjchandler** [comment]
Okay, so I'll use the SKU of the variant to determine if it should be deleted, because obviously we don't have access to the UUIDs of the one that need to be deleted since they're not in the request.

**Comment by duncanmcclean** [comment]
> Okay, so I'll use the SKU of the variant to determine if it should be deleted, because obviously we don't have access to the UUIDs of the one that need to be deleted since they're not in the request.

The user can change the SKU though so that might not be the best way to do it. Might be an idea to just add a hidden field in their for UUIDs and use that. UUIDs will never change.

**Comment by ryangjchandler** [comment]
> > Okay, so I'll use the SKU of the variant to determine if it should be deleted, because obviously we don't have access to the UUIDs of the one that need to be deleted since they're not in the request.
> 
> The user can change the SKU though so that might not be the best way to do it. Might be an idea to just add a hidden field in their for UUIDs and use that. UUIDs will never change.

But surely using the SKU would have the same effect if they HAVE to be unique. The UUID's have to be unique, and if there's no possible way

**Comment by ryangjchandler** [comment]
Didn't mean to close 😕

**Comment by ryangjchandler** [comment]
> > Okay, so I'll use the SKU of the variant to determine if it should be deleted, because obviously we don't have access to the UUIDs of the one that need to be deleted since they're not in the request.
> 
> The user can change the SKU though so that might not be the best way to do it. Might be an idea to just add a hidden field in their for UUIDs and use that. UUIDs will never change.

Yeah, could add the hidden field but there would be the same problem as the attributes. Any new variants that get added in the same request won't have a UUID in the request, so they would get deleted too.

**Comment by duncanmcclean** [comment]
Could we not save it to the database with a UUID before making the comparison?

**Comment by ryangjchandler** [comment]
~~Yeah, but the request that we are using to compare it too would still not have that data.~~ Scrap that, I'm being an idiot. I can do this using the UUID, I could also change the attributes one to use UUID instead of key value comparisons.
