### ISSUE TITLE
Fix resource table styling

### ISSUE THREAD

**Issue by ryangjchandler** [duncanmcclean/simple-commerce#167]
### Description

The tables that the addon provides in the CP are currently flat and are missing some styles compared to the default Statamic ones. See screenshots below:

Addon:

![image](https://user-images.githubusercontent.com/41837763/74593745-7e875880-5026-11ea-91cc-f7c8e1d53134.png)

Statamic:

![image](https://user-images.githubusercontent.com/41837763/74593746-86df9380-5026-11ea-9529-83eb59062745.png)

**Comment by ryangjchandler** [comment]
Happy to throw a PR in for this btw.

**Comment by duncanmcclean** [comment]
Yeah sure. This is one of the things on my list after Jack's design updates yesterday on Beta 15.

**Comment by duncanmcclean** [comment]
By the way, when you're doing this beware that there are listings in loads of places, views, vue components, fieldtypes.

**Comment by ryangjchandler** [comment]
> By the way, when you're doing this beware that there are listings in loads of places, views, vue components, fieldtypes.

In which case, maybe makes sense for you to do this one. I'm bound to miss something.

**Comment by duncanmcclean** [comment]
OK, will do!
