### ISSUE TITLE
Product Images

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#171]
### Description
I think that it would be a good idea to introduce product images so the customer can see what they're buying.

Images are always quite an important part of a product page so I'm thinking it could be something we could build into Simple Commerce instead of letting developers make something.

One thing I'm not sure about is - would the images belong on the variant or on the product. 

For example, a product could have images of different sides and then a variant could have photos to show off that specific variant.

Which would be a better fit?

**Comment by johncarter-** [comment]
I think the option to have inheritance from the "parent" product would be best. In fact that level of inheritance could be extended to price and attributes too. For example, it would be tedious to add the same image / brand attribute to each variant when it could be inherited from the parent, unless overridden at the variant level. Especially if you have like 10+ variants ( no uncommon in clothing and footwear ).

**Comment by ryangjchandler** [comment]
> I think the option to have inheritance from the "parent" product would be best. In fact that level of inheritance could be extended to price and attributes too. For example, it would be tedious to add the same image / brand attribute to each variant when it could be inherited from the parent, unless overridden at the variant level. Especially if you have like 10+ variants ( no uncommon in clothing and footwear ).

+1, Yeah, inheritance by default but still provide a way to override for each variant too.

**Comment by duncanmcclean** [comment]
@ryangjchandler Given how Simple Commerce is built, how do you think would be the easiest way to build the inheritance stuff?

Ideally I'd like the images to be part of the attributes system but not sure if that would work..

**Comment by duncanmcclean** [comment]
Alright , I'm going to close this issue now as it can probably be managed with product and variant attributes.
