### ISSUE TITLE
Hook into Algolia search

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#174]
### Description
I think that it would be a good idea if Simple Commerce could hook into Algolia search, from [Statamic core](https://statamic.dev/search#algolia).

It would give developers a better way of filtering products and provide real-time search results.

The only issue I can see with this is that it might require Simple Commerce to hook everything into the Stache. If this is true, we'll probably have to implement this later on down the road.

**Comment by ryangjchandler** [comment]
I think this is something that should live in userland or as an additional package, it doesn't seem very core worthy.

**Comment by duncanmcclean** [comment]
> I think this is something that should live in userland or as an additional package, it doesn't seem very core worthy.

Hmm, I'm not sure about that. Statamic bakes in Algolia support in core and I think that Simple Commerce should do the same thing. 

But if you've got a reason why you think it would be better in a separate package, let me know 😃
