### ISSUE TITLE
Shipping Zone country not displayed

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#191]
### Description

Can not add a shipping zone because when selecting a country, country field remains blank.

### Steps to reproduce

1. Select country France (or any country)
<img width="347" alt="image" src="https://user-images.githubusercontent.com/27975/77787303-a0312200-705f-11ea-8874-8a8534333811.png">

2. Country field is empty
<img width="607" alt="image" src="https://user-images.githubusercontent.com/27975/77787371-bccd5a00-705f-11ea-94cd-d76ec50d766a.png">

<img width="210" alt="image" src="https://user-images.githubusercontent.com/27975/77787707-4aa94500-7060-11ea-801c-a6248508ab4b.png">

When saving, response is HTTP 422 with an error on country_id:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/27975/77787828-83491e80-7060-11ea-9122-e3018091e811.png">

### Additional information

* Statamic version: 3.0.0-beta.20
* Simple commerce version: 1.0.0-beta.10
* PHP version: 7.4.3
* Other addons: none

**Comment by duncanmcclean** [comment]
Thanks for reporting! I'll have a look into this on Monday. My suspicion is that it's a Statamic bug.

**Comment by zedix** [comment]
Thanks you.  It seems that the issue is that field name sent is "country" when you expect a "country_id" instead in your validation rules.

**Comment by duncanmcclean** [comment]
Oh ok, I'll have a look on Monday. 👍

**Comment by duncanmcclean** [comment]
Fixed both issues. I should get a release out soon with them in.
