### ISSUE TITLE
Variant: error on SKU field when editing

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#192]
### Description

When editing a product variant, the SKU field always returns this error: "This value has already been taken."

### Steps to reproduce

1. Edit any product variant
2. Try to edit any field such as "name" then click "Save"

<img width="832" alt="image" src="https://user-images.githubusercontent.com/27975/77788432-8abcf780-7061-11ea-9d58-95f18b63a6c4.png">

Can not save because the SKU field is displayed in error (422).

<img width="294" alt="image" src="https://user-images.githubusercontent.com/27975/77788722-0cad2080-7062-11ea-8eac-53e982d1c732.png">

### Additional information

* Statamic version: 3.0.0-beta.20
* Simple commerce version: 1.0.0-beta.10
* PHP version: 7.4.3
* Other addons: none

**Comment by duncanmcclean** [comment]
Thanks for your report! Spotted this myself today.
