### ISSUE TITLE
Variant: saved attributes are not displayed when editing

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#193]
## Description

Attributes related to a product variant are successfully saved in the database but are not displayed when editing the product.

## Steps to reproduce

1. Edit a product then add some attributes

<img width="788" alt="image" src="https://user-images.githubusercontent.com/27975/77791027-2e100b80-7066-11ea-81bf-c18066aa6dd3.png">

2. Click "Save"

The attributes are not displayed anymore: 

<img width="584" alt="image" src="https://user-images.githubusercontent.com/27975/77790889-e5585280-7065-11ea-87ec-8fc22666f6f5.png">

While saved in the database:

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/27975/77790862-d8d3fa00-7065-11ea-94c4-d53c09ff8536.png">

## Additional information

* Statamic version: 3.0.0-beta.20
* Simple commerce version: 1.0.0-beta.10
* PHP version: 7.4.3
* Other addons: none

**Comment by duncanmcclean** [comment]
Thanks for reporting! 

Although, it's a duplicate of #89.
