### ISSUE TITLE
Abandoned Cart Support

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#207]
## Describe the feature
From a marketing perspective, it would be nice to know who hasn't completed their checkout (abandoned cart) and send them a series of follow up emails at a pre-defined interval. E.g., maybe send them a follow up X days later, another follow up Y days later and a final reminder Z days later (maybe even a coupon code)

**Comment by duncanmcclean** [comment]
Thanks for the issue!

My thinking right now is that this might be integrated as a separate addon that is not part of Simple Commerce's core.

**Comment by duncanmcclean** [comment]
Again, like those other two issues I feel like this shouldn't be something implemented as part of the addon, instead of on the site itself or through an another addon.
