### ISSUE TITLE
Maxmind integration

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#210]
## Describe the feature
Verify purchases for fraud via the basic (free) and paid MaxMind APIs. Chargebacks are SUPER expensive and should be avoided if possible

**Comment by duncanmcclean** [comment]
Hey, I don't really want to integrate third-party things directly into Simple Commerce core, I want to keep it as clean as possible.

The Stripe gateway is an exception to this rule but I'm in the process of extracting it to its own package/addon in the next few days.

Your best solution would probably be building something yourself, in a package or just right into your site. Let me know if you need any help while doing that.
