### ISSUE TITLE
Asset fields in product or variant attributes - stack is broken

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#218]
## Describe the bug
When you add an `Asset` field to product or variant's attributes fieldset and you try to open the asset browser, the stack is broken, like the screenshot

## Expected behaviour
I expected the asset browser stack to open correctly.

## Screenshots or Flare
Add some screenshots or a link to see the exception in Flare.
![image](https://user-images.githubusercontent.com/19637309/78889719-23894500-7a5c-11ea-88f5-9b2594e6f64d.png)

**Comment by zedix** [comment]
Just tested as a variant attribute. I confirm this is broken for existing products but seems OK for new products.

Additionally, saving an image seems broken too. Value is saved in the attributes table (e.g. `["assets::some-image.png"]`) and correctly passed to publish-form in the `values` but do not show up when editing the product: `assets` field contains no images.

**Comment by duncanmcclean** [comment]
> Just tested as a variant attribute. I confirm this is broken for existing products but seems OK for new products.
> 
> Additionally, saving an image seems broken too. Value is saved in the attributes table (e.g. `["assets::some-image.png"]`) and correctly passed to publish-form in the `values` but do not show up when editing the product: `assets` field contains no images.

Huh, that's strange. 

When we save it to the database we cast it as JSON and it *should* return back in it's normal format but I can tell that's not what's happening 😢 

I'll have a look on Tuesday when I'm back at work.

**Comment by zedix** [comment]
Just some thoughts : maybe the `Assets` field should be part of the simple-commerce Core fields ? (it's a bit wierd for a commerce addon to let user add a Product without handling images out-of-the box)

I would probably attach an `Assets` field to each variants, with maybe a notion of _default_ image for each collection of assets. This should also be accessible inside {{ variants }} in antlers templates, in order to build the Product gallery of images.

**Comment by duncanmcclean** [comment]
I made a change yesterday to fix the way some data was being passed from the controller into the publish forms so I think that should fix the fieldset issue in the next release.

I also agree that there should be a 'Gallery' field or similar on products/variants. Not sure if it's a change I'd make in the upcoming release, probably due sometime early next week or the one after that.

**Comment by duncanmcclean** [comment]
Closing - an image field will be added to variants in the next release.
