### ISSUE TITLE
Product bundles

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#219]
Group products together to offer a bundle discount

**Comment by duncanmcclean** [comment]
This might hook into the discounting functionality I'm planning on building in #147

**Comment by duncanmcclean** [comment]
For now, I'm not going to build product bundles into the core of Simple Commerce, until I see if there's greater demand for this feature.

However, I have written some documentation for how you can make product bundles work with a custom controller.

https://simple-commerce-docs.netlify.app/knowledge/product-bundles.html

**Comment by sbrow** [comment]
> https://simple-commerce-docs.netlify.app/knowledge/product-bundles.html

This link appears to be dead. Is the content still available somewhere?

**Comment by duncanmcclean** [comment]
That link has been dead for about 3/4 years at this point - it was written for v1, which was very short lived (v2 was a complete rewrite so the docs were re-done).

There's no alternative docs for it.

**Comment by de-raaf-media** [comment]
I am very interested to know how to achieve this with a custom controller. What would be the approach to get this to work with V2? I am not asking for the complete code but what direction were you thinking in V1?

**Comment by duncanmcclean** [comment]
I've thrown together a quick example of how I might implement it. It will likely need some changes & testing on your end but hopefully it's a decent starting place.

Example: https://gist.github.com/duncanmcclean/4f485d6f60b6ed197b1a7612dd4d65fa

In my example, I have a controller which adds the bundle products to the customer's cart. Then, in my `AppServiceProvider`, I'm using the [dynamic pricing](https://simple-commerce.duncanmcclean.com/dynamic-pricing) feature to check if all bundle products still exist in the cart and if so, apply the bundle discount to those products.
