### ISSUE TITLE
Mailing list integration

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#220]
Automatically subscribe users to a mailing list (in an appropriate list) based on the products they purchase. This could feature Sendy and Mailcheap support

**Comment by duncanmcclean** [comment]
This isn't something I'm planning on integrating as part of Simple Commerce core. It's something I'd recommend building for your specific use case by listening for Simple Commerce events etc. 

There are Statamic addons for marketing software like [Mailchimp](https://statamic.com/addons/silentz/mailchimp) but not sure if they'd have any way of integrating with Simple Commerce, you'd have to contact the addon developers about that.
