### ISSUE TITLE
Variant inheritance from parent

### ISSUE THREAD

**Issue by johncarter-** [duncanmcclean/simple-commerce#227]
A variant should inherit data from the parent product with the option to override it at a variant level.

I.e. A parent product has a price of £100, I don't want to add that price to all the variations of that product, so if I don't set it it should cascade from the parent. Same with images, etc.

**Comment by duncanmcclean** [comment]
How would you rather inheritance being done? Like at the data level in your templates?

**Comment by johncarter-** [comment]
Yeah I think so - I don't really know enough about it - but I assume you could have custom tags.

**Comment by duncanmcclean** [comment]
Had a play around with this sort of stuff this morning, it already seems possible if you're using the `{{ simple-commerce:product }}`tag on your product pages. 

Say you had a product field called `operating_system`. You could use that while you're looping round variants. Like this:

```
{{ simple-commerce:product }}
  {{ variants }}
    <h1>{{ name }}</h1> <!-- outputs the variants name -->
    <p>{{ operating_system }}</p> <!-- would inherit from product if variant doesn't have field with same handle -->
  {{ /variants }}
{{ /simple-commerce:product }}
```

Is this the sort of thing you mean? Maybe I'm misunderstanding you.

**Comment by duncanmcclean** [comment]
I'm going to close this issue for now. If you encounter any issues with this in the future, feel free to comment and I'll consider re-opening.
