### ISSUE TITLE
Policies do not accept App\User models

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#235]
Policies do not accept App\User models and throw an error when not beeing a Super user.

Policies should accept an `Illuminate\Database\Eloquent\Model;`

Note: if you are a super user, all permissons are ignored because of this: https://github.com/statamic/cms/blob/master/src/Providers/AuthServiceProvider.php#L76

<details>
  <summary>Steps to reproduce</summary>
  
  1. Go to the CP page /cp/users
  2. Dont be a Super user but have ''view products' permissions
  3. Error is: `Argument 1 passed to DoubleThreeDigital\SimpleCommerce\Policies\ProductPolicy::view() must be an instance of Statamic\Auth\User, instance of App\User given`
</details>

<details>
  <summary>Environment information</summary>
  
  **Simple Commerce version:** v1.0.0-beta-18

  **Statamic version:** 3.0.0.-beta-28

  **PHP version:** 7.4

  **Operating System:**
  - [X] MacOS
  - [ ] Linux
  - [ ] Windows

  **Browser:**
  - [X] Chrome
  - [X] Firefox
  - [X] Safari
</details>

**Comment by duncanmcclean** [comment]
Thanks for reporting! Fixed the issue, will be pushed out in the next release.

**Comment by zedix** [comment]
Thanks Duncan.

But I guess it will not work if you use another model than the default one `'model' => \App\User::class;`

I suggest to replace: `use App\User` by `use Illuminate\Database\Eloquent\Model as User`; to accept any customer user class;

**Comment by duncanmcclean** [comment]
> Thanks Duncan.
> 
> But I guess it will not work if you use another model than the default one `'model' => \App\User::class;`
> 
> I suggest to replace: `use App\User` by `use Illuminate\Database\Eloquent\Model as User`; to accept any customer user class;

Good catch. I've added a patch with your suggestion.
