### ISSUE TITLE
Permission 'edit products' do no work

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#236]
Permission 'edit products' do no work because into CP `ProductController#edit`, `$this->authorize('update', $product);`is called on a UUID string instead of a Product class;

Dump of `$ability`, `$args` & `AuthorizationException` in `CpController#authorize`:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/27975/81562206-ba675b00-9394-11ea-99fe-43b26288f7d1.png">

Fix:

```php
public function edit($product)
{
    $crumbs = Breadcrumbs::make([['text' => 'Simple Commerce'], ['text' => 'Products', 'url' => cp_route('products.index')]]);

    $product = Product::with('variants', 'attributes')
        ->where('uuid', $product)
        ->first();

    $this->authorize('update', $product);
    // ...
}
```

<details>
  <summary>Steps to reproduce</summary>
  
  1. Have  'edit products' permission (do not be a super user)
  2. Edit a product
  3. Permisssion is denied 

<details>
  I expect to be able to edit  a product when having 'edit products' permission.
</details>

<details>
  <summary>Environment information</summary>
  
  **Simple Commerce version:** v1.0.0-beta-19

  **Statamic version:** 3.0.0.-beta-28

  **PHP version:** 7.4

  **Operating System:**
  - [X] MacOS
  - [ ] Linux
  - [ ] Windows

  **Browser:**
  - [X] Chrome
  - [X] Firefox
  - [X] Safari
</details>

**Comment by zedix** [comment]
Please note also that `$this->authorize('update', Order::class);` should be `$this->authorize('update', $order);`. You probably want to add unit tests on permissions.

To test permissions, you have to _not be_ a "super" user. When beeing a "super" user, no permissions are ever called because Statamic has a Gate::before in AuthServiceProvider that always returns `true` when `$user->isSuper();`, which stop the process of further calls to policies.

```php
Gate::before(function ($user, $ability) {
    return optional(User::fromUser($user))->isSuper() ? true : null;
});
```

**Comment by duncanmcclean** [comment]
I've just fixed the issue. I'll try and write some permission tests this afternoon for critical parts of the CP. Thanks for your help.
