### ISSUE TITLE
Incorrect currency formatting and missing raw value

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#242]
You should not parse the currency yourself (Currency::parse) but use a CLDR instead (PHP Intl `NumberFormatter`).

In example, for the 'fr-FR' locale, EUR must be formatted using '€' with a no-break space before it. Therefore, `$total.$symbol` is incorrect.

You can quickly test it with JavaScript using `Intl.NumberFormat`:

```js
console.log(new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(12.00));
// 12,00 €
```

In PHP, you can use for example:

```php
public function formatCurrency($amount)
{
    $fmt = new NumberFormatter(config('app.locale'), NumberFormatter::CURRENCY);
    $fmt->setAttribute(NumberFormatter::FRACTION_DIGITS, 2);
    $fmt->setAttribute(NumberFormatter::MIN_FRACTION_DIGITS, 2);
    $fmt->setAttribute(NumberFormatter::MAX_FRACTION_DIGITS, 2);
    $fmt->setAttribute(NumberFormatter::DECIMAL_ALWAYS_SHOWN, 1);

    return $fmt->formatCurrency($amount, config('simple-commerce.currency.iso'));
}
```

You should also pass the **raw price** to front-end as well as we may want :
- to display another formatted amount using user local currency
- to use another formatting style
- to use Offer microdata such as:

```html
<meta itemprop="priceCurrency" content="EUR" />
<meta itemprop="price" content="{{ price }}" />
```

In VariantData:
```php
$data['price] = <original float value>
$data['price_formatted'] = Currency::format($original->price);
```

<details>
  <summary>Steps to reproduce</summary>
  
  1. Have a config with:
```
    'currency' => [
        'iso' => 'EUR',
        'position' => 'right', // Options: left, right
        'separator' => ',',
    ],
```

  2. Display a variant price
  3. Actual: 

<img width="572" alt="image" src="https://user-images.githubusercontent.com/27975/81955983-0d4a4800-960b-11ea-994c-bc6663fadaea.png">
</details>

<details>
  <summary>Expected behaviour</summary>
 Expected: 5,00 €
</details>

<details>
  <summary>Environment information</summary>
  
  **Simple Commerce version:** v1.0.0-beta-20

  **Statamic version:** 3.0.0.-beta-28

  **PHP version:** 7.4

  **Operating System:**
  - [X] MacOS
  - [ ] Linux
  - [ ] Windows
</details>

**Comment by duncanmcclean** [comment]
Hey, thanks for the issue!

From my understanding of the issue, you're having issues when outputting currency amounts where there's no spacing between currency stuff? You also think that we should be using the `NumberFormat` thing to do our currency formatting?

Ideally, I'd prefer to keep the `Currency::parse()` function there, but maybe it could just be smarter about that sort of stuff.

If you're willing, I'd love to see a pull request of how you'd like it to work and we could work from there😄.

**Comment by damcclean** [comment]
Also, just added a `unformatted_total` property which can be used to avoid the variant total being parsed by Simple Commerce.

**Comment by duncanmcclean** [comment]
As this is an issue regarding Simple Commerce v1 which is no longer in active development I'm going to close this issue.

However, if you're having issues with this, feel free to re-open this issue.
