### ISSUE TITLE
Blueprint application directory should not be changed by simple-commerce

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#243]
In a Statamic application, you can only have **one** single blueprint directory for the all application. I'm using a custom directory that is setup in my AppServiceProvider : 
`StatamicBlueprint::setDirectory(resource_path('my/custom/path/to/blueprints'));`

Therefore, this directory shoud _never_ be changed by simple-commerce. 

Currently, in every simple-commerce models, we find:

```php
public function blueprint()
{
    return Blueprint::setDirectory(__DIR__.'/../../resources/blueprints')
        ->find('xxx');
}
```

This shoud not touch the directory and only use:

```php
public function blueprint()
{
    return Blueprint::find('xxx');
}
```

Simple-commerce blueprints should probably be published (again) and controlled by the application.

Here's another use case requiring control of the simple-commerce blueprints app-side:

**Actual:**
- Try to change the disk `container` of the images field (in product > variants) to use a custom one:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/27975/82151707-1d596600-985d-11ea-92cc-6b0fd509f603.png">
- This can not be saved

**Expected:**
- The change is saved in `my/custom/path/to/blueprints/product` blueprint file.

<details>
  <summary>Environment information</summary>
  
  **Simple Commerce version:** v1.0.0-beta-20

  **Statamic version:** 3.0.0.-beta-28

  **PHP version:** 7.4

  **Operating System:**
  - [X] MacOS
  - [ ] Linux
  - [ ] Windows
</details>

**Comment by duncanmcclean** [comment]
Thanks for creating the issue.

My thinking behind not publishing the blueprints to the user's `resources/blueprints` anymore is that I can see it being an issue in the future where users would add their own field there or modify existing ones and expect everything to *just work* and for the fields to be saved to the database. If the user wants to add a field, I would advise they do that in the provided fieldsets.

However, I can see your use case, where you want to change the asset container that is attached to the Product Image field.

Maybe what I could do is add the image field to the default variant fieldset so the user could modify (or even remove) it from there? What do you think?

**Comment by zedix** [comment]
Hi Duncan. 

I understand the rationale behind it. Even if I see more simple-commerce like the jack's _idea_ behind the new "statamic starter kits" : starting point for your app, leave the user do whatever he want with it - do not try to keep control.

Users having basic needs will not change the published blueprints anyway. And users touching them probably knows what they do and the consequences. For those reasons, I will probably go for publishing the blueprints. 

By the way, you probably have to for now as Statamic Blueprint can only handle _one_ directory (and only _one_ fallback directory). Therefore, calling `setDirectory` in your code is still an issue as it change the blueprints directory globally. 

Also, in any real-world commerce application, sooner or later, you may have business requirements, even small, that will make you want to add or extend some stuffs (maybe the order of the fields, maybe the coupon fields, or maybe you just want to a new variant field with a real column in the `variants` table instead of an attribute to be more "searchable" in example).

Another solution that may work would be to have configurable models:

```php
'models' => [
    'Product' => \App\Product::class,
    'Order' => \DoubleThreeDigital\SimpleCommerce\Models\Order::class,
    // ...
],
```

So in my case, i could change the blueprint() method using:

```
class Product extends \DoubleThreeDigital\SimpleCommerce\Models\Product
{
    public function blueprint()
    {
        return Blueprint::find('product');
    }

    // More extends as you wish
}
```
