### ISSUE TITLE
Cart quantity should be constrained by the variant maxQuantity

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#246]
When calling multiple times `addToCart` with a product variant having a `maxQuantity = 1`, quantity can be higher than the `maxQuantity`.

## Steps to reproduce

1. Add to cart a product with `maxQuantity` = 1
2. Add to cart again
3. Quantity equals 2; it should stay 1.

## Expected behaviour

Cart quantity should not be higher than `maxQuantity` allowed.

## Environment information

**Simple Commerce version:** v1.0.0-beta-20

**Statamic version:** 3.0.0.-beta-28

**PHP version:** 7.4

**Operating System:**
- [X] MacOS
- [ ] Linux
- [ ] Windows

**Browser:**
- [X] Chrome
- [X] Firefox
- [X] Safari

**Comment by duncanmcclean** [comment]
Thanks for reporting!

I think I've found a fix for this but before I implement it, could you just confirm it works?

The change is in line 78 of `src/Support/Cart.php`.

Currently the line is `if ($quantity > $variant->max_quantity) {`, could you change that to `if ($quantity >= $variant->max_quantity) {` and try again?

Thanks for your help!

**Comment by zedix** [comment]
With your change, result is now an Exception: ` You are not allowed to add more than 1 of this item.`. 

It may be better to just cap the quantity with no exception thrown:

```php
$lineItem->update([
   'quantity' => $quantity >= $variant->max_quantity ? $variant->max_quantity : $lineItem->quantity + $quantity,
]);
```
