### ISSUE TITLE
Exception Currency::parse() on cart view

### ISSUE THREAD

**Issue by vanhooff** [duncanmcclean/simple-commerce#250]
Cart view currently throws an exception.

## Steps to reproduce

1. Fresh install with demo content
2. Add item to cart
3. Go to cart page
4. you'll get the following exception:
```
Facade\Ignition\Exceptions\ViewException
Argument 1 passed to DoubleThreeDigital\SimpleCommerce\Support\Currency::parse() must be of the type float, string given, called in /Users/myuser/Projects/ecommerce-starter/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261
```
## Expected behaviour

A working cart view

## Environment information

**Simple Commerce version:** v1.0.0-beta-22

**Statamic version:** 3.0.0.-beta-29

**PHP version:** 7.4.4

**Operating System:**
- [x] MacOS
- [ ] Linux
- [ ] Windows

**Browser:**
- [x] Chrome
- [ ] Firefox
- [ ] Safari

**Comment by vanhooff** [comment]
After some further inspection, i think it is some concatenation issue in Currency.php from line 41. If i remove the concatenated $symbol it works as expected.

**Comment by duncanmcclean** [comment]
Did you use the starter kit?

**Comment by vanhooff** [comment]
Tried both starter and clean package

**Comment by duncanmcclean** [comment]
OK, did you run `php please simple-commerce:install` when installing either time? After running the migrations, that command also seeds your database with currencies.

I'll try and confirm this bug in a bit.

**Comment by vanhooff** [comment]
Yep! See here for further inspection: https://8b0cfdc44c00.eu.ngrok.io/cart

**Comment by duncanmcclean** [comment]
Cool. I'll try and reproduce the bug manually.

**Comment by duncanmcclean** [comment]
Found the bug! On Line 51 of `cart.antlers.html`, remove the `price` modifier from `total`. That should do it!

**Comment by vanhooff** [comment]
Yep, that fixed it!

**Comment by duncanmcclean** [comment]
Cool. Basically the `price` modifier turns a raw number into a string that's the number but formatted with the symbol, separator etc. But `total` was already a formatted string which means it's not a raw number, if you get what I mean. 😂
