### ISSUE TITLE
When Debugbar is enabled checkout throws an exception.

### ISSUE THREAD

**Issue by vanhooff** [duncanmcclean/simple-commerce#251]
When Debugbar is enabled checkout throws an exception.

## Steps to reproduce

1. .env > DEBUGBAR_ENABLED=true 
2. add item to cart and go to checkout
3. Throws exception:
```
Facade\Ignition\Exceptions\ViewException
'Variables' is already a registered collector
```

## Expected behaviour
Working checkout view

## Environment information

**Simple Commerce version:** v1.0.0-beta-22
**Statamic version:** 3.0.0.-beta-29
**PHP version:** 7.4.4

**Operating System:**
- [x] MacOS
- [ ] Linux
- [ ] Windows

**Browser:**
- [x] Chrome
- [ ] Firefox
- [ ] Safari

**Comment by duncanmcclean** [comment]
Thanks for your issue! Don't think I've seen this issue before. I'll have a look now.

**Comment by duncanmcclean** [comment]
Also, just to confirm - what gateways do you have installed? could you share that part of the `config/simple-commerce.php` file with me?

**Comment by vanhooff** [comment]
Sure: 
```
'gateways' => [
        \DoubleThreeDigital\SimpleCommerce\Gateways\DummyGateway::class => [],
    ],
```

**Comment by duncanmcclean** [comment]
This sucker seems to be the file causing trouble.... https://github.com/statamic/cms/blob/master/src/View/Debugbar/AddVariables.php

I wonder how I can fix it... 🤔

**Comment by duncanmcclean** [comment]
Fixed @sandervanh! Turns out I was returning the gateway view wrong. Sorry about that.
