### ISSUE TITLE
Tax Rates UI panel do not show any labels

### ISSUE THREAD

**Issue by zedix** [duncanmcclean/simple-commerce#254]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/27975/85743725-94a7d280-b704-11ea-8b75-bd61d746674d.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/27975/85743903-bbfe9f80-b704-11ea-985c-13e0c3f16aef.png">

![image](https://user-images.githubusercontent.com/27975/85743665-85c12000-b704-11ea-994e-9a23efbca928.png)

## Steps to reproduce

1. Have Tax Rates configurated
2. Create a new product's variant and open Tax Rate panel

No labels are displayed.

## Expected behaviour

Labels are displayed.

## Environment information

**Simple Commerce version:** v1.0.0-beta-24
**Statamic version:** 3.0.0.-beta-31
**PHP version:** 7.4

**Operating System:**
- [x] MacOS
- [ ] Linux
- [ ] Windows

**Browser:**
- [ ] Chrome
- [x] Firefox
- [ ] Safari

**Comment by duncanmcclean** [comment]
Will be fixed in the next release.
