### ISSUE TITLE
Tax not calculated correctly

### ISSUE THREAD

**Issue by Hesesses** [duncanmcclean/simple-commerce#265]
Quick description of the bug...

Tax not calculated correctly

## Steps to reproduce

config:
```
return [
    'sites' => [
        'default' => [
            'currency' => 'EUR',

            'tax' => [
                'rate' => 24,
                'included_in_prices' => true,
            ],
...

<span>{{ sc:cart:taxTotal }}</span>
```
![image](https://user-images.githubusercontent.com/2721970/87850204-20bdac00-c8f7-11ea-973c-c02c0cce2de1.png)

## Expected behaviour

I expected the tax row would show 23,76e (99 *0.24)

**Comment by duncanmcclean** [comment]
This should work if you change `included_in_prices` to being `false`, then the tax should work. 

Although, tax might be something I need to consider doing some more work on, likely after release.

**Comment by Hesesses** [comment]
I think it makes more sense when product price is 100:

```
'included_in_prices' => false`,
'rate' => 24,

Price 100
Tax    24
Total 124
```

```
'included_in_prices' => true`,
'rate' => 24,

Price 100
Tax    24
Total 100
```

```
'included_in_prices' => true`,
'rate' => 0,

Price 100
Tax     0
Total 100
```

**Comment by duncanmcclean** [comment]
Okay, how would you expect the tax functionality to work? Just so I can work on improving it.
