### ISSUE TITLE
Customize receipt and order confirmation

### ISSUE THREAD

**Issue by Hesesses** [duncanmcclean/simple-commerce#266]
Would be good if you can replace the receipt.blade.php / order-confirmation.blade.php with your own.

I would like to change the layout and also use translations.

**Comment by duncanmcclean** [comment]
This functionality will be included in the next release.

You'll be able to publish the views with this command:

```
php artisan vendor:publish --tag=simple-commerce-views
```

Then the views will live in your `resources/views/vendor/simple-commerce` file and you can edit them from there.
