### ISSUE TITLE
Creating a new order after a successful order

### ISSUE THREAD

**Issue by Hesesses** [duncanmcclean/simple-commerce#267]
Sometimes when I have created a new order, then I go back to my products page and add product to cart (which redirects checkout page) I'm getting the following error:

`Call to a member function id() on null`

![image](https://user-images.githubusercontent.com/2721970/87872048-33e77f00-c9be-11ea-920c-4414ff91ac79.png)

**Comment by Hesesses** [comment]
I tried to reproduce this without success, but noticed that if the error above wont happen and I can make the 2nd order successfully. Then the first order will be overwritten by the details of 2nd order.

**Comment by duncanmcclean** [comment]
How did you create the order, just with the addItemToCart tag?

**Comment by Hesesses** [comment]
```
{{ sc:cart:addItem redirect='/checkout' }}
  <input type="hidden" name="product" value="{{ id }}">
  <input type="hidden" name="sku" value="test-1">  
  <input type="hidden" name="quantity" value="1">
  <button class="inline-block w-full py-3 px-5 my-5 leading-none text-center text-white bg-indigo-500 hover:bg-indigo-600 rounded shadow">click</button>
{{ /sc:cart:addItem }}
```

**Comment by duncanmcclean** [comment]
If you run into the issue again, could you please add steps to reproduce so I can have a look at why it's not working. Thanks 😃

**Comment by Hesesses** [comment]
1. open site on incognito browser
2. go to products page
3. add product to cart and redirect to checkout
4. fill details
5. purchase completed (order #1)
6. go to products page
7. add product to cart and redirect to checkout
8. fill details (same email)
9. purchase completed (order #2)
10. add product to cart and redirect to checkout
11. fill details (different email)
12. purchase completed

13. Order #1 is overwritten by the details from the last order (step 11)

**Comment by duncanmcclean** [comment]
> 1. open site on incognito browser
> 2. go to products page
> 3. add product to cart and redirect to checkout
> 4. fill details
> 5. purchase completed (order #1)
> 6. go to products page
> 7. add product to cart and redirect to checkout
> 8. fill details (same email)
> 9. purchase completed (order #2)
> 10. add product to cart and redirect to checkout
> 11. fill details (different email)
> 12. purchase completed
> 13. Order #1 is overwritten by the details from the last order (step 11)

Thanks! I'll try and get round to this issue this evening when I'm free. I think I know exactly what the issue is 😄

**Comment by duncanmcclean** [comment]
Fix has now been released! 🎉 https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.0.0-beta.4
