### ISSUE TITLE
Error thrown on empty cart

### ISSUE THREAD

**Issue by TracerBuilt** [duncanmcclean/simple-commerce#275]
After installing a new site and updating through 'composer update', if you attempt to navigate to the empty cart in the browser it returns a TypeError stating:

>Argument 1 passed to DoubleThreeDigital\SimpleCommerce\Repositories\CartRepository::find() must be of the type string, null given, called in [directory]/rad-ecommerce-store/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261

**Comment by duncanmcclean** [comment]
Fixed in latest release. Also, might want to add this line to the top of your cart & shipping pages so the user is redirected if they don't currently have a cart.

```
{{ if {sc:cart:has} === false }}
    {{ redirect to='/' }}
{{ /if }}
```
