### ISSUE TITLE
Unable to reedem coupon

### ISSUE THREAD

**Issue by sebabal** [duncanmcclean/simple-commerce#276]
Hey guys I am unable to redeem coupons I have this on the front end:

```html
{{ if {sc:coupon:has} === true }}
	{{ sc:coupon }}
	<div class="flex flex-col mb-2 py-2">
		<h3 class="font-bold text-lg mb-2 text-gray-800">Coupon</h3>

		<div>
			<p class="inline-block"><strong class="font-bold uppercase">{{ slug }}</strong> has been applied
				to your cart.</p>
			{{ sc:coupon:remove class='inline-block' }}
			<button class="text-red-700 font-medium focus:outline-none ml-1" type="submit">Remove</button>
			{{ /sc:coupon:remove }}
		</div>
	</div>
	{{ /sc:coupon }}
	{{ else }}
	{{ sc:coupon:redeem id='redeemCoupon' }}
	<div class="flex flex-col mb-2 py-2">
		<h3 class="font-bold text-lg mb-2 text-gray-800">Redeem a Coupon</h3>

		<div class="flex flex-row items-start w-full">
			<input class="md:w-2/3 border rounded p-2 mb-2 text-gray-600 focus:text-gray-800 outline-none mr-2"
				type="text" name="code" placeholder="Coupon Code" value="{{ old:code }}" required>
			<div x-data="{ loading: false }" class="md:w-1/3 flex flex-row items-center">
				<button x-show="loading === true"
					class="bg-primary hover:bg-tertiary py-2 px-6 uppercase text-white font-bold w-full h-full flex flex-row items-center justify-center"
					type="button">
					<i class="fal fa-spinner-third fa-spin mr-2"></i> Processing
				</button>

				<button x-show="loading === false"
					class="bg-primary hover:bg-tertiary py-2 px-6 uppercase text-white font-bold w-full h-full"
					type="button"
					x-on:click.prevent="loading = true; document.getElementById('redeemCoupon').submit()">
					Redeem
				</button>
			</div>
		</div>
	</div>
	{{ /sc:coupon:redeem }}
{{ /if }}
```

I looked at the response and I am not getting anything back so I am not sure if it is being processed correctly. Have you experienced anything similar?

## Environment information

**Simple Commerce version:** v2.0

**Statamic version:** 3.0.0-beta.43

**PHP version:** 7.4.3

**Operating System:**
- [ ] Linux

**Browser:**
- [ ] Chrome

**Comment by duncanmcclean** [comment]
Thanks for reporting!

Could you share the file of the coupon you're trying to redeem?

**Comment by sebabal** [comment]
Duncan, here are the coupon and the blueprint

[sherpa.txt](https://github.com/doublethreedigital/simple-commerce/files/5068982/sherpa.txt)
[coupon.txt](https://github.com/doublethreedigital/simple-commerce/files/5068983/coupon.txt)

**Comment by duncanmcclean** [comment]
They seem okay. What are you trying to use as the coupon code?

**Comment by sebabal** [comment]
The coupon code I am trying to redeem is called "sherpa". Here are some screenshots, the post is going through, although I am not getting a response but perhaps that is by design and there is no response....

![redeemui](https://user-images.githubusercontent.com/210946/90136772-11d9e600-dd4b-11ea-8ec3-739392ff5575.jpg)
![post](https://user-images.githubusercontent.com/210946/90136781-16060380-dd4b-11ea-99ef-8642e5df08af.jpg)
![data](https://user-images.githubusercontent.com/210946/90136789-17cfc700-dd4b-11ea-9721-8bd4017ee23e.jpg)
![response](https://user-images.githubusercontent.com/210946/90136792-1a322100-dd4b-11ea-9df2-28c741d6d58d.jpg)

**Comment by duncanmcclean** [comment]
Alright, looks like it was a little validation error in Simple Commerce. It was checking for a `coupon` field, where the rest of the code and the starter kit examples used the `code` field instead. 

I'll push out a fix for this in the next release. Thanks for reporting!
