### ISSUE TITLE
Composer "update" issues

### ISSUE THREAD

**Issue by sebabal** [duncanmcclean/simple-commerce#278]
Everytime I do a "composer update" the settings are getting overwritten.

Also now I am getting an "Unable to locate publishable resources". See attached screenshot.

![image](https://user-images.githubusercontent.com/210946/90425642-77550c00-e096-11ea-9a73-4d1511937aa7.png)

## How to reproduce

1. Run composer update

## What I expected

I would like to keep my settings intact on each update

## Environment

Statamic 3.0.0-beta.44 Pro
Laravel 6.18.35
PHP 7.4.3
No addons installed

**Comment by duncanmcclean** [comment]
Darn. Statamic does some auto-publishing stuff, I'll try to get round that in the next update. Sorry about that.

**Comment by duncanmcclean** [comment]
Fixed in 27cf51b
