### ISSUE TITLE
[Feature Request] Driver-based cart system

### ISSUE THREAD

**Issue by ryangjchandler** [duncanmcclean/simple-commerce#282]
One improvement of the current system would be having a driver-based system for the cart ID storage. For example, when working with the current `SessionCart`, to change the storage location you would need to change the `SESSION_DRIVER` too.

**Comment by duncanmcclean** [comment]
Jumping back into this issue: could you provide any cases where a developer may choose to use a different driver for the cart?

**Comment by duncanmcclean** [comment]
I'm closing this issue as I'm not exactly sure where it would come in useful. If a developer was to build their store headless or a mobile app for example, they could probably build themselves an alternative to the `SessionCart` driver that we have built in.
