### ISSUE TITLE
[Feature Request] Add the ability to add metadata to an order

### ISSUE THREAD

**Issue by sebabal** [duncanmcclean/simple-commerce#289]
I would like to have the ability to add metadata (defined in the blueprints) to an order, customer, etc from the different cart forms, like "checkout" and "cart"

**Comment by duncanmcclean** [comment]
This will be added in the next release! 

As long as you're in the cart or checkout forms, you can basically send any form fields and if they don't conflict with anything needed by Simple Commerce then it'll be passed into your order data.

And for customers... you can send customer data as an array in the form and it'll be saved to either a new customer or an existing customer (depending on what can be found for the email address). One thing to remember though is that you'll need to pass in an email, like is done below.

```
{{ sc:cart:update }}
<!-- These fields will be passed to the customer entry - remember the email -->
<input type="text" name="customer[name]">
<input type="text" name="customer[email]">
<input type="text" name="customer[favourite_colour]">

<!-- And these fields will be passed as fields to the order entry -->
<input type="text" name="some_random_field">
{{ /sc:cart:update }}
```

Once this is released, I'll get this functionality documented.
