### ISSUE TITLE
one item in cart

### ISSUE THREAD

**Issue by mmorkt** [duncanmcclean/simple-commerce#290]
When adding product to cart it overwrites the existing product in the cart. There are never more then one product in the cart

## How to reproduce
Install Simple Commerce and the boilerplate 

## What I expected
More then one product in cart

## Environment
Nitro (Multipass) environment (Local)
Statamic 3.0.0 Solo
Laravel 7.25.0
PHP 7.4.9
doublethreedigital/simple-commerce 2.0.11

**Comment by duncanmcclean** [comment]
Good catch, thanks for reporting! I'll get that fixed.
