### ISSUE TITLE
[Feature Request]  Email notification 

### ISSUE THREAD

**Issue by mmorkt** [duncanmcclean/simple-commerce#291]
Hi, 

At the moment the client gets an email notifications but the admin doesn't. 
It would be nice having a user notification when a order is placed, when running a small shop.

**Comment by duncanmcclean** [comment]
I'm currently planning on implementing this in v2.1.0. Until then, if you need to implement this you could hook into the `CartCompleted` event and send an email yourself.

**Comment by duncanmcclean** [comment]
This feature has been implemented in v2.1 which I'm hoping to release at some point in the next two weeks. I'm closing this card for now to clean up Github issues. I'll update this card once the update has been released.

**Comment by duncanmcclean** [comment]
I'm back!! Just to update you like I promised, [v2.1 has just been tagged](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.1.0) and with it comes some basic back-office reporting that notifies staff when an order has been paid for. 

Hopefully this is helpful. I'm planning on adding other back-office notifications in the future.
