### ISSUE TITLE
No Stripe customer info is sent

### ISSUE THREAD

**Issue by sebabal** [duncanmcclean/simple-commerce#292]
Although the payment goes through, no other metadata is being sent, like email, name, addresses, etc.

This is pretty important in order for Stripe to able to send email receipts and create customers on their end.

Is there a way you can send this data?

## Environment

Statamic 3.0.0 Pro
Laravel 6.18.35
PHP 7.4.3
aryehraber/statamic-recaptcha dev-statamic-3
doublethreedigital/duplicator 1.0.5
doublethreedigital/simple-commerce 2.0.11
statamic/migrator dev-master

**Comment by duncanmcclean** [comment]
Good idea, I can see that being pretty essential. 

I'll aim to add it in for the next release.

**Comment by sebabal** [comment]
Thanks! Also can you tweak the payload sent so that the description is actually the Product Title right now it seems to be the payment intent ID or something like that

![image](https://user-images.githubusercontent.com/210946/91339941-9433c280-e7ad-11ea-847f-56158e607f77.png)

**Comment by sebabal** [comment]
Sorry no the product title but the order title/number etc

**Comment by duncanmcclean** [comment]
Coming in the next release. It should hopefully be a bit more helpful.

**Comment by sebabal** [comment]
I see now that the Description includes the order title, but the email, name, etc are still not going through....

**Comment by duncanmcclean** [comment]
For a customer to be created in Stripe and added to the order, you'll need to have created a customer before using the '{{ sc:checkout }}' tags which calls the gateway prepare method (where the customer is created)

**Comment by sebabal** [comment]
I have the following inside the '{{sc:checkout}}'

```html
<input class="" type="text"name="name" placeholder="Full Name" value="{{ old:name }}" required>
<input class="" type="email"	name="email" placeholder="Email" value="{{ old:email }}" required>
<input class="" type="text" name="customer[company]" placeholder="Company Name" value="{{ old:company }}" required>
```

The customer on statamic gets created correctly but not on Stripe...

**Comment by duncanmcclean** [comment]
Ahh...

For the customer to be sent to Stripe, you'll need to create the customer beforehand, like in the cart update tag.

It's because we send the information to Stripe before loading the checkout form (so we can get the intent). 

Hopefully that's helpful!

**Comment by sebabal** [comment]
Duncan, so I need to put the field on both forms?

**Comment by duncanmcclean** [comment]
You'll only need it on the cart update one.

**Comment by sebabal** [comment]
The problem is that I need to ask the same information on the checkout form otherwise I get undefined index for email, name I am guessing I need to put those hidden with the submitted value? Do I have access to those after being redirected to the checkout page?

**Comment by duncanmcclean** [comment]
Hmm, I’ll have a look at the Stripe API tomorrow but I’m not sure there’s a way around it unless you split the steps up as the customer needs to be on the order before the checkout tag for the intent to work.

**Comment by duncanmcclean** [comment]
If you need the customer data on the checkout page, you should be able to get it. I’ll just need to double check the syntax for that.

**Comment by sebabal** [comment]
No I do not need that it seems the SC needs that, I only want to ask for the info once.
