### ISSUE TITLE
If client doesn't exist in checkout it breaks

### ISSUE THREAD

**Issue by mmorkt** [duncanmcclean/simple-commerce#296]
Hi! 
It seems like the checkout breaks if the client doesn't exist as an existing customer in "Customers". The auto generated title is null. Getting this error:
```
TypeError
Typed property DoubleThreeDigital\SimpleCommerce\Repositories\CustomerRepository::$title must be string, null used 

DoubleThreeDigital\SimpleCommerce\Repositories\CustomerRepository::find
vendor/doublethreedigital/simple-commerce/src/Repositories/CustomerRepository
```

## How to reproduce
Checkout with a mailadress that haven't been used in the system yet.

## What I expected
Getting confirmation.

**Comment by sebabal** [comment]
I second this...was able to replicate it too.

**Comment by duncanmcclean** [comment]
Good call! I'll get that fixed up for the next release.

**Comment by duncanmcclean** [comment]
Fixed!

**Comment by mmorkt** [comment]
Just a follow up on this issue. The title isn't generated, but the confirmation works

**Comment by duncanmcclean** [comment]
> Just a follow up on this issue. The title isn't generated, but the confirmation works

Are both the name and email fields set?
