### ISSUE TITLE
[Feature Request] Mollie Payment Gateway

### ISSUE THREAD

**Issue by octoper** [duncanmcclean/simple-commerce#297]
Add Mollie Payment Provider out of the box!

**Comment by duncanmcclean** [comment]
I'm planning on implementing this as pert if v2.1.0.

**Comment by duncanmcclean** [comment]
Just a question: what's the main reasoning behind wanting to use Mollie as a payment gateway, instead of say Stripe?

**Comment by octoper** [comment]
I have seen that European companies are using it because 1-2 years before Stripe wasn't available in many European countries as is now.

**Comment by octoper** [comment]
Also I'll be happy to help you implement this I can make a pull request in some days if you want.

**Comment by duncanmcclean** [comment]
Cool!

I'm planning on implementing it in the next big version and I'm also going to re-do the gateway stuff then as well. However, if you'd like it before then, feel free to make a pull request!

**Comment by duncanmcclean** [comment]
Just want to leave an update on this feature request.... I'm mostly done building the Mollie gateway, which will be released as part of v2.1 of Simple Commerce. 

I've opened a pull request for it, #297.

**Comment by duncanmcclean** [comment]
This feature has been implemented in v2.1 which I'm hoping to release at some point in the next two weeks. I'm closing this card for now to clean up Github issues. I'll update this card once the update has been released.

**Comment by duncanmcclean** [comment]
Here's the update I said I would make.... [v2.1 has just been released](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.1.0)!

And... it comes with the built-in Mollie gateway 😅  There's some documentation covering it, [over here](https://sc-docs.doublethree.digital/v2.1/gateways#builtin-gateways)! Enjoy.
