### ISSUE TITLE
Getting "Class 'NumberFormatter' not found" when trying to view product entry

### ISSUE THREAD

**Issue by twd3** [duncanmcclean/simple-commerce#303]
Using this:
```
{{ collection:products }}
{{ title }}
{{ price }}
{{ /collection:products }}
```
As well as this on my layout:
```
<a class="" href="{{ link to='/cart' }}">
{{ sc:cart:total }}
{{ sc:cart:count }}
</a>
```
When viewing page that has this one product I get "Class 'NumberFormatter' not found". I don't know which one of these tags is causing this. Or maybe if my install didn't go right?

## What I expected

To see product title and price?

## Environment

Statamic 3.0.11 Pro
Laravel 7.26.1
PHP 7.4.6
doublethreedigital/simple-commerce 2.0.15
optimoapps/statamic-bard-text-align 1.0.0
spatie/statamic-responsive-images 1.2.3

**Comment by duncanmcclean** [comment]
It'll be coming from prices or totals. They all go through the same currency formatter which uses that class. I'm not in front of the Simple Commerce codebase right now... but I think I may have a fix if you're willing to try it:

In your `vendor/doublethreedigital/simple-commerce/src/Repositories/CurrencyRepository.php` file, try changing `NumberFormatter` to `\NumberFormatter` on line 30.

Let me know how that goes.

**Comment by twd3** [comment]
It was ```$numberFormatter = new NumberFormatter('en_US', \NumberFormatter::CURRENCY);```
I changed to ```$numberFormatter = new \NumberFormatter('en_US', \NumberFormatter::CURRENCY);```
But didn't fix.

**Comment by duncanmcclean** [comment]
Hmm okay. It sounds like you're missing a PHP extension. From the looks of things, it's the `intl` extension. 

I'm not sure how to set it up specifically for your setup but Googling around should help you. Hopefully that's helpful, let me know how you get on.

**Comment by duncanmcclean** [comment]
I'm going to close this issue as the `intl` extension is listed in the addon's documentation (https://doublethree.digital/simple-commerce/installation) as a system requirement.

Let me know if that doesn't solve it and I'll re-open this issue.

**Comment by twd3** [comment]
Nope, you got it. I'm using Xampp so I just had to enable extension in php.ini...THANKS!
