### ISSUE TITLE
Are coupon codes working as of now?

### ISSUE THREAD

**Issue by twd3** [duncanmcclean/simple-commerce#304]
I made a coupon entry. A percentage based and I entered 20 for twenty percent (you don't need a percentage sign right). The product was $1000. When I applied the code it made the price in the cart over 4k?

## Environment

Statamic 3.0.12 Pro
Laravel 7.26.1
PHP 7.4.6
doublethreedigital/simple-commerce 2.0.15
optimoapps/statamic-bard-text-align 1.0.0
spatie/statamic-responsive-images 1.2.3

**Comment by duncanmcclean** [comment]
That doesn't sound right. I'll have a look.

**Comment by duncanmcclean** [comment]
I've just attempted to re-create this issue but it seemed to work correctly for me, see below screenshots.

Could you send me the coupon entry file along with the product entry file that you're testing with? Either pop them in here or send them via email, [duncan@doublethree.digital](mailto:duncan@doublethree.digital).

![image](https://user-images.githubusercontent.com/19637309/94169159-631ae080-fe86-11ea-827f-374f141b418c.png)

![image](https://user-images.githubusercontent.com/19637309/94168521-a294fd00-fe85-11ea-81dd-d9c308ef74ef.png)

**Comment by twd3** [comment]
So sorry it took me so long to get back to you. I just tested again last night and I am still having an issue. It must be something I'm doing? Here is my coupon:
```
---
title: Testing20
type: percentage
value: '20'
minimum_cart_value: 0
redeemed: 0
updated_by: 724953a3-eef1-41f9-be61-a2
updated_at: 1600816298
id: aff99656-80d3-461c-bf52-924f76c7ca7e
---

```

**Comment by duncanmcclean** [comment]
Very strange. I just copied that coupon into my testing site and redeemed it on a $1000 product and it works properly (the total takes $200) off.

I tried on both my existing testing site and a fresh one, it worked on both. What does your `config/simple-commerce.php` file look like?

**Comment by twd3** [comment]
```
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Sites
    |--------------------------------------------------------------------------
    |
    | For each of your Statamic sites, you can setup a new store which allows you
    | to use different currencies, tax rates and shipping methods.
    |
    */

    'sites' => [
        'default' => [
            'currency' => 'USD',

            'tax' => [
                'rate'               => 20,
                'included_in_prices' => false,
            ],

            'shipping' => [
                'methods' => [
                    //\DoubleThreeDigital\SimpleCommerce\Shipping\StandardPost::class,
                ],
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Gateways
    |--------------------------------------------------------------------------
    |
    | You can setup multiple payment gateways for your store with Simple Commerce.
    | Here's where you can configure the gateways in use.
    |
    */

    'gateways' => [
       // \DoubleThreeDigital\SimpleCommerce\Gateways\DummyGateway::class => [],
		\DoubleThreeDigital\SimpleCommerce\Gateways\StripeGateway::class => [
            'key' => env('STRIPE_KEY'),
            'secret' => env('STRIPE_SECRET'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Notifications
    |--------------------------------------------------------------------------
    |
    | Simple Commerce can automatically send notifications to customers after
    | events occur in your store. eg. a cart being completed.
    |
    | Here's where you can toggle if certain notifications are enabled/disabled.
    |
    */

    'notifications' => [
        'cart_confirmation' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Collections & Taxonomies
    |--------------------------------------------------------------------------
    |
    | Simple Commerce uses Statamic's native collections and taxonomies functionality.
    | It will automatically create collections/taxonomies upon addon installation if
    | they don't already exist. However, if you'd like to use a different collection
    | or taxonomy, like one you've already setup, here's the place to change that.
    |
    */

    'collections' => [
        'products'  => 'products',
        'orders'    => 'orders',
        'coupons'   => 'coupons',
        'customers' => 'customers',
    ],

    'taxonomies' => [
        'product_categories' => 'product_categories',
        'order_statuses'     => 'order_statuses',
    ],

    /*
    |--------------------------------------------------------------------------
    | Cart Key
    |--------------------------------------------------------------------------
    |
    | Under the hood, Simple Commerce sets an entry in the session to store the customers'
    | current cart ID. If you want to, you can change the key of the session entry.
    |
    */

    'cart_key' => 'simple-commerce-cart',

];
```

If it works on your install it must be something I am doing. I took the stuff from the starter kit and edited just a bit. I took the account step out of checkout because my users are already logged in when they add to cart. What should I be looking at? I think I might be allowing them to view cart within the checkout process? I'm going to try again tonight.

**Comment by duncanmcclean** [comment]
That looks like it should be fine and seems to be pretty similar to what I've got. Could you share the code for the coupon form you're using and the code for where you're displaying the totals.

**Comment by twd3** [comment]
I doubt this is a bug and more me trying to figure stuff out. To be clear, I have to do cart stuff BEFORE I hit checkout right? I think at one point I was trying to condense checkout by having cart and payment on same page. I am going to test tonight with Login > Add Product > View Cart > Checkout Process minus account. Love this addon BTW! Thanks.

**Comment by duncanmcclean** [comment]
> I doubt this is a bug and more me trying to figure stuff out. To be clear, I have to do cart stuff BEFORE I hit checkout right? I think at one point I was trying to condense checkout by having cart and payment on same page. I am going to test tonight with Login > Add Product > View Cart > Checkout Process minus account. Love this addon BTW! Thanks.

I've not tested having everything in one big page yet but I'd recommend splitting the cart and the checkout if you can, having the coupons and shipping being managed inside the cart page and then having the checkout for the payment.

However, I'm not sure that having everything in a single page would affect something like what you're seeing but it's technology, so you never know. 🤷‍♂️

No problem!

**Comment by twd3** [comment]
So weird...I just tested again using the flow I detailed above. Again this is how it goes:
1: They Login
2: They add to cart:
```
{{ sc:cart:addItem redirect="/cart" }}
<input type="hidden" name="product" value="96a4e71d-6384-495a-93d3-B7a5">
<input class="hidden" type="number" name="quantity" value="1">
<h1>Items for: {{ user }}{{ name }}{{ /user }}</h1>
<input id="Submit" type="submit" name="submit_button" value="NEXT">
{{ /sc:cart:addItem }}
```
They get redirected to cart as you can see.
Then the cart code is an exact copy of the one you supply. I enter testing20 in coupon area, hit redeem and get this:
![Firefox_Screenshot_2020-09-29T00-55-05 783Z](https://user-images.githubusercontent.com/16004958/94500313-451dea80-01bc-11eb-8fe0-0199e519460e.png)

What in the world did I mess up lol.

**Comment by duncanmcclean** [comment]
Hmm, something weird is definitely happening there. 

If you want to, could you zip your products, coupons and views folders and email them to me so I can have a greater look - duncan@doublethree.digital.

**Comment by duncanmcclean** [comment]
Figured it out! Somehow decimal numbers were messing stuff up. I've made sure to remove decimal numbers and convert them to integers. 

I've just tagged a new release to fix this bug, [v2.0.17](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.0.17). 🎉

**Comment by twd3** [comment]
Confirm, fixed. Good job! Your support rules!

**Comment by duncanmcclean** [comment]
Awesome!! Glad I could help.
