### ISSUE TITLE
Customer title and slug not being generated

### ISSUE THREAD

**Issue by twd3** [duncanmcclean/simple-commerce#311]
If you look at a successful order in the CP the customer that the order is linked to looks weird (see screenshot). If I look at the order .md file there is a customer id on it that is the correct customer id.

![Untitled-1](https://user-images.githubusercontent.com/16004958/95023006-c7ccfc80-0637-11eb-950f-15a60cbbb1be.jpg)

**Comment by duncanmcclean** [comment]
This looks more like a Statamic issue, rather than one with Simple Commerce. 

What does your order blueprint look like, have you changed the handle of your customers collection, what does the customer's entry look like, does it have a title?

**Comment by twd3** [comment]
Yeah, when does this title come in? My customer has no title but when I try to edit in cp says title is required. Haven't changed any handles. No title...

Cust entry:
```
---
name: 'Test User'
email: test@test.net
id: 8f53fd18-eaeb-40c9-a186-9f857709c42c
published: false
---
```

**Comment by duncanmcclean** [comment]
That'll be it then. The title is what is displayed in the fieldtype but since you don't have a title on the entry, it's blank/empty.

To be honest, I would have thought it would have been required but obviously not. You should be able to add one manually anyway, it doesn't matter what it is.

Simple Commerce doesn't really do anything with the titles, other than generating them if one doesn't already exist when it does a Customer entry lookup.

**Comment by duncanmcclean** [comment]
I think the reason it has a blank title was because of the issue we had earlier where it wasn't checking if the title and slug existed properly. Normally, one should be generated.

**Comment by twd3** [comment]
When does it create the customer? Shouldn't it inject something in title if it's required? Oh, okay, one should be generated?

**Comment by twd3** [comment]
As far as I know right now I would have to add something like ```name="customer[title]"``` to update the customer through sc:cart:update...

**Comment by duncanmcclean** [comment]
Yeah, it should have been generated, it just wasn't because of that bug.

The customer is created when you pass in a name and email to the `cart:create` tag.

**Comment by twd3** [comment]
Oh so statamic bug?

**Comment by duncanmcclean** [comment]
> As far as I know right now I would have to add something like `name="customer[title]"` to update the customer through sc:cart:update...

I'm not sure if that'll work currently but you can give it a shot, I have a funny feeling it might.

You can also update customers outside of orders, as long as you have the customer's ID, [see documentation](https://sc-docs.doublethree.digital/tags#customer)

**Comment by duncanmcclean** [comment]
> Oh so statamic bug?

It was the bug we had earlier where it wasn't checking for null values, just empty ones. If you create a new customer now, a title and slug should be generated for it.

**Comment by twd3** [comment]
Oh, I thought I did that last test after fully updating. I'll try again on a new customer not that same old test@test.net.

**Comment by twd3** [comment]
Still no title being generated with brand new customer. I never tried adding the ```name="customer[title]"``` to the email step like I have name and email now. I see title is not required in the customers bp.

**Comment by duncanmcclean** [comment]
I'll have a play around with it tonight/tomorrow. It should be generating whenever a new customer is created 🤔

**Comment by duncanmcclean** [comment]
Turns out whenever a customer is updated, it lost the title which was weird. I've fixed that in [v2.0.22](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.0.22).

Have a good night!

**Comment by adriaanglibert** [comment]
I still have the same issue even on the latest version of Statamic and Simple Commerce..

- "statamic/cms": "3.3.60"
-  "doublethreedigital/simple-commerce": "^4.2.3",

**Comment by duncanmcclean** [comment]
@adriaanglibert Please open a new issue.
