### ISSUE TITLE
Mollie gateway redirect

### ISSUE THREAD

**Issue by JanJanssensDigiti** [duncanmcclean/simple-commerce#327]
Hi!

I was trying out the mollie gateway for simple commerce but after the payment has been marked as succesfull I get following exception. It seems that the /!/simple-commerce/gateways/mollie/callback redirect tries to return the 'gateway_does_not_exist' message. When dumping the array that has been given I get following array.

Currently running v2.1.23. 

![Schermafbeelding 2021-01-04 om 17 04 02](https://user-images.githubusercontent.com/73839128/103554337-0aa8a580-4eaf-11eb-893e-30da192cce29.png)

![Schermafbeelding 2021-01-04 om 16 32 39](https://user-images.githubusercontent.com/73839128/103553766-337c6b00-4eae-11eb-9e4a-d074162797ff.png)

**Comment by duncanmcclean** [comment]
Thanks. I'll have a look at it now.

**Comment by duncanmcclean** [comment]
I've just pushed out a release which should resolve this issue for you! [v2.1.24](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.1.24)

**Comment by JanJanssensDigiti** [comment]
> I've just pushed out a release which should resolve this issue for you! [v2.1.24](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.1.24)

Thanks for the quick response!
