### ISSUE TITLE
Mollie payment is being called multiple times

### ISSUE THREAD

**Issue by JanJanssensDigiti** [duncanmcclean/simple-commerce#329]
![Schermafbeelding 2021-01-05 om 14 02 11](https://user-images.githubusercontent.com/73839128/103650365-2fa92100-4f60-11eb-809b-a713b0d8aa45.png)

## How to reproduce

I just used the tag from the documentation to call the offsite gateway from Mollie.
`{{ sc:checkout:mollie redirect="/thanks" }}`

This it sends multiple requests and causes a few problems:
- Redirecting back to the site can't be done with the parameter you set. Redirecting falls back on the failsafe you have put in release 2.1.24
- Orders aren't being updated on the is_paid status

I'm seriously considering to dive in a bit more in package development to help you a bit because i'm now just putting a lot of work on your shoulders :sweat_smile:

## Environment

Statamic 3.0.36 Pro
Laravel 8.20.1
PHP 7.4.13
doublethreedigital/simple-commerce 2.1.24

**Comment by duncanmcclean** [comment]
That's certainly not intended. I'll have a look into those issues this evening.

**Comment by duncanmcclean** [comment]
Regarding the `is_paid` not updating, you'll need to setup a webhook on your Mollie account to `/!/simple-commerce/gateways/mollie/webhook`. 

But for that you'll need the URL to be publicly accessible (mollie needs to send data to your site) which you can use something like Ngrok or [Expose](https://beyondco.de/docs/expose/introduction) for.

**Comment by JanJanssensDigiti** [comment]
Okay finally had some time to test this. The redirect issue has indeed been solved!
 
I did a change in the mollie gateways because you can't set a predefined webhook in the mollie dashboard like you can in Stripe. The webhook isset in your payment request so I solved that with the code below. 

/src/Gateway/MollieGateway.php line:40
`'webhookUrl'  => route('statamic.simple-commerce.gateways.webhook', ['mollie']),`

You also have to disable CSRF verification for the mollie webhook to work. I currently did this in the App Middleware VerifyCsrfToken Class but don't know if it is possible to add such an exception in your package. After this the webhook is being send but gets an error 500. It is throwing the same exception like in issue #327. Below you will find the log from the server.

I also found that the duplicating requests in mollie are created if you put the sc:checkout:mollie tag within the sc:gateway tag so that was my bad. Mollie still receives 2 requests each time you use sc:checkout:mollie. It is not a breaking bug so it isn't that important but I thought I just report it to you.

[error_20210108-1336.log](https://github.com/doublethreedigital/simple-commerce/files/5787662/error_20210108-1336.log)

**Comment by duncanmcclean** [comment]
Awesome! Glad the redirect is fixed.

If you wouldn't mind, could you create a pull request for the change you made? 

With the CSRF issue, that's not something I can throw an exception for as it would never actually reach Simple Commerce if there's no token. But I'll make sure to document that.

Thanks for reporting all of these issues! I'll hopefully be able to look over these issues over the weekend.

**Comment by duncanmcclean** [comment]
Alright, I think I've managed to track down and fix all of the bugs you've brought up in this issue.

The reason multiple orders were being created was down to the way the Simple Commerce tags work, as technically with a normal tag you can't do `{{ sc:gateways:mollie }}`, you can only do `{{ sc:gateways }}`, so we have to splice it up and forward them to the right code, that's the bit that was going wrong.

Regarding webhooks - I've updated where the Webhook URL is set from, as it was sometimes returning as `null`. I've now hard coded the URL because it's never really going to change. I've also added some documentation around [gateway webhooks](https://sc-docs.doublethree.digital/v2.1/gateways#using-webhooks), including noting the fact you'll need to add a CSRF exception.

I've pushed out a new release with these bug fixes: [v2.1.26](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.1.26). 

Hopefully that's all of the issues resolved. Please let me know if anything's still causing issues.

**Comment by JanJanssensDigiti** [comment]
Tested your changes in 2.1.26. The multiple orders issue is indeed fixed 🎉

but i'm still running into the webhook failing. I thought I could fix it like you did in #327 with the GatewayCallback. That's the code you see below.

`<?php

namespace DoubleThreeDigital\SimpleCommerce\Http\Controllers;

use DoubleThreeDigital\SimpleCommerce\Exceptions\GatewayDoesNotExist;
use DoubleThreeDigital\SimpleCommerce\Facades\Gateway;
use DoubleThreeDigital\SimpleCommerce\SimpleCommerce;
use Illuminate\Http\Request;

class GatewayWebhookController extends BaseActionController
{
    public function index(Request $request, $gateway)
    {
        $gateway = collect(SimpleCommerce::gateways())
            ->where('handle', $gateway)
            ->first();

        if (! $gateway) {
            throw new GatewayDoesNotExist(__('simple-commerce::gateways.gateway_does_not_exist', [
                'gateway' => $gateway['name'],
            ]));
        }

        return Gateway::use($gateway['class'])->webhook($request);
    }
}`

After this the webhook is indeed being reached which it wasn't doing before but then I'm running into the following error when it is trying to fetch the order.

`Too few arguments to function Illuminate\Support\Collection::get(), 0 passed in /data/sites/web/ofyrshop/checkout/main/8bb31250fe00ba167f7543c660dee757bee4a8eb/www/vendor/doublethreedigital/simple-commerce/src/Gateways/MollieGateway.php on line 128 and at least 1 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function Illuminate\\Support\\Collection::get(), 0 passed in /data/sites/web/ofyrshop/checkout/main/8bb31250fe00ba167f7543c660dee757bee4a8eb/www/vendor/doublethreedigital/simple-commerce/src/Gateways/MollieGateway.php on line 128 and at least 1 expected at /data/sites/web/ofyrshop/checkout/main/8bb31250fe00ba167f7543c660dee757bee4a8eb/www/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:405)`

I already tinkered with it a bit but can't get this fixed. 😕  Otherwise I would have put this one also in a PR and relieve you of this work 😅

**Comment by duncanmcclean** [comment]
Would you mind creating a new issue about the webhooks issue?

**Comment by JanJanssensDigiti** [comment]
Yes np! ;)
