### ISSUE TITLE
Cart Item Removal Issue

### ISSUE THREAD

**Issue by tonybyng** [duncanmcclean/simple-commerce#346]
Hi

Im using the tag {{ sc:cart:count }} to show how many items are in the cart. If nothing has been added to the cart, it works (shows 0), if something is in the cart, it works (shows 1, 2 etc) , but if Ive added to the cart and then removed from the cart so that I now have no items in the cart I get 

ErrorException
Undefined index: items

I expected it to produce a 0 count

Thanks

**Comment by duncanmcclean** [comment]
Hey,

Could you copy and paste the output of `php please support:details` so I know which Statamic and Simple Commerce versions you're using?

Thanks

**Comment by tonybyng** [comment]
Hi

Thanks for the fast response ! Im running on localhost and have got the pro flag set while Im developing.

Statamic 3.0.40 Pro
Laravel 8.22.1
PHP 7.4.3
aerni/social-links 2.1.0
aryehraber/statamic-impersonator 2.1.0
austenc/socialize 1.0.0
doublethreedigital/sc-digital-products 1.0.6
doublethreedigital/simple-commerce 2.1.32
gioppy/statamic-aggregate-assets 0.0.2
gioppy/statamic-metatags 1.0.2
pecotamic/sitemap 1.1.0
simonridley/tracking-code-manager dev-master
spatie/statamic-responsive-images 1.8.0
statamic/ssg dev-master

**Comment by duncanmcclean** [comment]
Thanks!

I think I also run into this bug myself the other day and I think I fixed it in v2.2.0. However, it looks like I forgot to also fix it in v2.1. I'll get that fixed and tagged this evening.

**Comment by tonybyng** [comment]
Im only just getting used to statamic and I thought the Updates menu showed an indicator when any of the addons had updates as well. Ive just seen you released 2.2.0 2 days ago so I will update - no need to fix in 2.1, My bad.

**Comment by duncanmcclean** [comment]
In actual fact, turns out I had fixed the bug in [v2.1.35](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.1.35) (you were using v2.1.32).

I've also just copied the same fix over to v2.2 as well, which I'll tag a release for shortly.
