### ISSUE TITLE
Prevent negative cart and quantity values

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#354]
A quick description of the issue you're facing.

If the user sets a negative quantity, the total cart cost will be negative.

## How to reproduce

specify a negative quantity

## What I expected

negative value is turned to a postive value

## Environment

Copy the output of `php please support:details` into here.

**Comment by duncanmcclean** [comment]
From the next release, only quantities over 0 will be allowed. If the quantity is less than 0, a validation error will be thrown.
