### ISSUE TITLE
Undefined index: variant

### ISSUE THREAD

**Issue by philpasquin** [duncanmcclean/simple-commerce#366]
I get this error every time I try to add to the cart. :
``ErrorException Undefined index: variant``

 I tried with products that have variants and some that don't and I always get the same error.

Is it me that missed something here?

**Comment by duncanmcclean** [comment]
Would you mind giving me some more information about the issue?

1. Your Simple Commerce version (you can get it by running `php please support:details`)
2. The error's stack trace, it'll be available in the browser or at the bottom of your log file.

Also, little note for the future, please use the provided issue template, it helps to get all the appropriate information first time round.

Thanks 🙂

**Comment by philpasquin** [comment]
Dumb mistake, everything good.

**Comment by duncanmcclean** [comment]
Awesome! I think this was actually fixed in a recent release so if it comes up again, might be worth updating.
