### ISSUE TITLE
Session Driver: Cart Key exception

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#368]
```
Facade\Ignition\Exceptions\ViewException
Return value of DoubleThreeDigital\SimpleCommerce\Orders\Cart\Drivers\SessionDriver::getCartKey() must be of the type string, null returned
```

If you can, please provide a screenshot of the issue or a link to the Flare exception, maybe even both.

## Environment

```
php please support:details
Statamic 3.0.44 Pro
Laravel 7.30.4
PHP 7.4.14
aryehraber/statamic-captcha 1.3.0
doublethreedigital/sc-digital-products 2.0.2
doublethreedigital/simple-commerce 2.2.11
statamic/seo-pro 2.1.1
```

**Comment by duncanmcclean** [comment]
When do you come across this issue? Also, are you using the session driver or the cookie driver?

**Comment by barchard** [comment]
I am seeing this on page load. Can't load my test environment right now. Config is:

```
    'cart' => [
        'driver' => \DoubleThreeDigital\SimpleCommerce\Orders\Cart\Drivers\SessionDriver::class,
        'key' => 'simple-commerce-cart',
    ],
```

**Comment by duncanmcclean** [comment]
Funnily enough, I had someone with this same exception earlier today which I put down to something else (#367).

However, I'm still unable to actually reproduce this issue myself. Are you using any cart related tags inside the template/layout for the page you're on? In case maybe it's an issue from there.

**Comment by duncanmcclean** [comment]
I've just pulled down your repository again and checked out the branch but I'm still not able to replicate 🤔 I've tried the homepage, product pages and in your `/cart` page.

Are you still running into this or has it magically gone away? If not, would you mind sending me the full stack trace, either on here or via email so I can see where the issue starts from?
