### ISSUE TITLE
Cart does not total

### ISSUE THREAD

**Issue by phpsa** [duncanmcclean/simple-commerce#374]
Shopping cart and checkout process do not total quantities. - this is using the starter kit you supplied.

![image](https://user-images.githubusercontent.com/952595/109250972-7d9b2080-784f-11eb-9fd6-4f848c1ac0a0.png)
![image](https://user-images.githubusercontent.com/952595/109251052-af13ec00-784f-11eb-9a9e-0d61b65dac4a.png)
![image](https://user-images.githubusercontent.com/952595/109251087-bc30db00-784f-11eb-871c-51311671278d.png)

**Comment by phpsa** [comment]
Notes that this seems to be only in the session driver

**Comment by phpsa** [comment]
Completely trashing my sessions / cookes and starting over seems to work on both.

**Comment by duncanmcclean** [comment]
Hmm, I'm not sure what happened. The grand total is calculated at the same time as the rest of the totals.

But anyway, glad it's kinda fixed now! 🙂
