### ISSUE TITLE
User can add QTY of 0 to cart

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#375]
## How to reproduce

Add to an item to the cart. Change item qty from 1 to 0. Item is still in the cart.

## What I expected

Item to be removed for qty < 1

**Comment by duncanmcclean** [comment]
By the sounds of it, you're adding an item to the cart with a quantity of 1, then you're updating the quantity to 0?

If that's right, I'm just about to commit some code which will throw a validation error if the quantity is less than 1. I'll push it out in the next release, likely this weekend when I've got some time to test & push it.
