### ISSUE TITLE
Stripe exception if checking out with $0

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#376]
## How to reproduce

try to check out with an item in your cart with 0 qty (and total $0)

![image](https://user-images.githubusercontent.com/17622/109851902-34b5e400-7c22-11eb-87f5-5e9be6a3e249.png)

## What I expected

checkout to show no items in your cart, not exception thrown

**Comment by duncanmcclean** [comment]
Yeah, Stripe won't generate a payment intent (which is required for Stripe Elements) if the amount is 0. You'll have to hide the checkout form, or redirect the user away from it, if the cart total is 0.

I've not tested it but maybe something like this will work?

```handlebars
{{ if {sc:cart:total} == 0 }}
    {{ redirect to="/" }}
{{ /if }}
```

I'm closing this issue now as there's not really anything I can do about it.
