### ISSUE TITLE
No validation is done on address fields

### ISSUE THREAD

**Issue by duncanmcclean** [duncanmcclean/simple-commerce#398]
## Description

When a user submits a cart update/checkout with their address, we should have someway of validating parts of the address are correct and aren't made up.

For example, we could validate the country code with our list and throw a validation error if the submitted country does not match.

## Environment

```
Statamic 3.0.48 Solo
Laravel 8.33.1
PHP 7.4.13
doublethreedigital/simple-commerce 2.2.16
```

**Comment by shawnsquire** [comment]
Hi, would there be a way for this to extend to other address fields? For example, we need a valid ZIP Code for delivery, and would like to have server-side validation that a ZIP code is valid.

Thanks!

**Comment by duncanmcclean** [comment]
> Hi, would there be a way for this to extend to other address fields? For example, we need a valid ZIP Code for delivery, and would like to have server-side validation that a ZIP code is valid.
> 
> 
> 
> Thanks!

Hey, would you be able to create a feature request for that?
