### ISSUE TITLE
Billing and Shipping details not pulling through to receipt.

### ISSUE THREAD

**Issue by anditopping** [duncanmcclean/simple-commerce#404]
## Description

The billing and shipping address details are not being output on the receipt. 

## Exact steps to reproduce
Place an order and the back office and customer confirmation are generated. The PDF attached to the Customer Confirmation doesn't show the Shipping or Billing Address, just the appropriate column titles.

## Environment
Statamic 3.0.46 Pro
Laravel 8.32.1
PHP 8.0.3
cnj/seotamic 2.0.3
doublethreedigital/simple-commerce 2.2.16

**Comment by duncanmcclean** [comment]
Fixed & tagged - [v2.2.18](https://sc-docs.doublethree.digital/v2.2/changelog#v2.2.18)

Have a nice evening 🎉

**Comment by anditopping** [comment]
Thanks Duncan!
