### ISSUE TITLE
Coupon Discounts do not get applied to the total amount te be payed

### ISSUE THREAD

**Issue by studiovlijmscherp** [duncanmcclean/simple-commerce#405]
When using a coupon code this should be applied to:
- {{ sc:cart:grandTotal }}
- total amount to be payed (using Mollie for example)

Both do not seem to be working

**Comment by duncanmcclean** [comment]
Thanks for helping me test! Fixed & tagged in [v2.2.19](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.2.19).
