### ISSUE TITLE
Deleting carts causes 500 errors for users who do not delete cookies

### ISSUE THREAD

**Issue by shawnsquire** [duncanmcclean/simple-commerce#416]
## Description

It seems deleting a Cart while the user still has the Cart assigned using the CookieDriver type will cause an unrecoverable 500 error. The only solution is having the user delete all cookies, use a new session, or recover the Entry.

The main issue happens on some antler tags that expect a cart, and the error was a Statamic "Entry not found" error for the Cart ID stored in the cookie that was deleted.

## Exact steps to reproduce

1. Use CookieDriver as the cart driver
2. Browse the site and trigger some action that generates a cart
3. Delete the cart from the Control Panel
4. Refresh the page

I had attempted to override the CookieDriver with one that treats deleted carts that do not exist as "missing" (e.g., returning false on `hasCart()`) but that does not seem to work on requests where the deleted cart is called on the same request where it checks if it's missing and creates it. I believe this is because the Cookie does not update until the request is completed, meaning that all references to the `getCart()` will refer to the **old** cookie value, which is the deleted cart. Therefore, this problem exists when trying to use the CookieDriver on any page which updates the cart.

## Temporary Fix

For now, I have fixed the problem temporarily by hacking together a Middleware to delete missing carts on every web request. Now it only seems to 500 under if it attempts to delete *and* read the cart in the same request, which are recoverable on refresh as it generates a new cart (which is bearable, as deleting a cart mid-processing is a Bad Move).

```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Cookie;
use Statamic\Facades\Entry;

class RemoveDeletedCart
{
    public function handle($request, Closure $next) {
        $response = $next($request);

        $cart_id = Cookie::get(Config::get('simple-commerce.cart.key'));
        if($cart_id != null && Entry::find($cart_id) == null) {
            Cookie::queue(Cookie::forget(Config::get('simple-commerce.cart.key')));
        }

        return $response;
    }
}
```

A different potential fix would be for all the Controllers to verify the cart exists both with the driver **and** as an Entry.

## Environment

Statamic 3.1.9 Pro
Laravel 7.30.4
PHP 7.4.16
4rn0/statamic-v3-image-optimizer 1.0.7
aryehraber/statamic-captcha 1.4.0
doublethreedigital/simple-commerce 2.2.20
edalzell/blade-directives 3.1
jimblue/mapbox 1.2.0
kautiontape/statamic-font-awesome dev-master
kautiontape/statamic-oh-dear 1.2.0
optimoapps/statamic-bard-text-align 1.0.2
statamic/migrator dev-master
statamic/seo-pro 2.2.0

**Comment by duncanmcclean** [comment]
Thanks for the detailed issue! I'll look through it properly this evening! 😄

**Comment by duncanmcclean** [comment]
Out of interest, why are you deleting the carts anyway?

**Comment by duncanmcclean** [comment]
Tagged a fix: [v2.2.21](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.2.21)

**Comment by shawnsquire** [comment]
> Out of interest, why are you deleting the carts anyway?

At first, because we generated a lot of fake testing carts when it went live to verify the process worked, and removed them to not complicate the Order table in the backend.

Later, the shop owners ran into the bug because they sell limited release products, which means a cart won't matter after the "run" of a product is over. They might not do this on the regular as they look at evergreen products, but for now it was causing issues for them.

**Comment by duncanmcclean** [comment]
Ah okay, that makes sense! If that happens again, the user should just end up with a fresh cart.
