### ISSUE TITLE
Additional / custom validation options when updating order (e.g., shipping fields validation)

### ISSUE THREAD

**Issue by shawnsquire** [duncanmcclean/simple-commerce#417]
## What would you like to see added?

The ability to customize the validation of specific fields, specifically the Address field to guarantee an Address is supplied and is valid. This should prevent an Order from being placed without a valid Address if desired.

## Is there a workaround you can use in the meantime?

No, other than client side validation, which isn't foolproof.

## Would you be open to PR'ing the feature?

Possibly, although I wouldn't know the best way to implement this while keeping the customization available.

---

If this is something you'd like to see added, please leave a 👍 reaction to this issue.

**Comment by duncanmcclean** [comment]
I'll have a proper look into this later. My initial thought is we could either hook into the blueprint's validation rules or we could add a hook so you can register your own validation rules.

**Comment by duncanmcclean** [comment]
I've been thinking about this over the last couple of days, trying to figure out the best way to make this customisable. Do you think adding validation rules to the fields in the blueprint would work for your use case?

**Comment by shawnsquire** [comment]
Thanks for taking the time to think about it. I think that should absolutely fit our use case, especially if it uses all the same validation rules (e.g., `required_if:`).

**Comment by duncanmcclean** [comment]
Awesome, I'll take a look at implementing this at the weekend, when I've got some spare time. 🙂

It'll probably make its way into v2.3.

**Comment by duncanmcclean** [comment]
This will be part of v2.3. Will probably push out a new beta release for it soon, the first one is out now.

It'll take the validation rules from your blueprint, minus a few like, the totals and the `items` field but it should be enough to allow you to do what you need to do.
