### ISSUE TITLE
Upgrade to 2.3 completely crashes if config is cached from 2.2

### ISSUE THREAD

**Issue by shawnsquire** [duncanmcclean/simple-commerce#421]
## Description

(First off, love the update, thanks for releasing it; I'm playing around with it because it has some major features we need)

The upgrade contains a reference to a `config` that may not exist if upgrading from an old version, causing a crash as it returns an invalid data type.

```
Return value of DoubleThreeDigital\SimpleCommerce\SimpleCommerce::orderDriver() must be of the type array, null returned
vendor/doublethreedigital/simple-commerce/src/SimpleCommerce.php:85
```

## Exact steps to reproduce

1. Use version 2.2.*
2. Cache your config using `php please config:cache`
3. Upgrade to 2.3 (currently beta) as described in release notes
4. Attempt to run the app or `php please` again
5. Witness the error above

## Steps to resolve

1. Downgrade back to 2.2.*
2. Uncache your config with `php please config:clear`
3. Upgrade to 2.3.*

## Environment

Statamic 3.1.11 Pro
Laravel 7.30.4
PHP 7.4.16
4rn0/statamic-v3-image-optimizer 1.0.7
aryehraber/statamic-captcha 1.4.0
doublethreedigital/simple-commerce 2.3.0-beta.2
edalzell/blade-directives 3.1
jimblue/mapbox 1.2.0
kautiontape/statamic-font-awesome dev-master
kautiontape/statamic-oh-dear 1.2.0
optimoapps/statamic-bard-text-align 1.0.2
statamic/migrator dev-master
statamic/seo-pro 2.2.0

**Comment by duncanmcclean** [comment]
Thanks for reporting! I don't use config caching so would have never caught this.

I think I can probably just clear the config cache before making changes and re-cache it afterwards (if it's turned on to start with). 

However, I'd say it's probably discouraged to even have config caching enabled in a development environment. (I'll make the fix anyway this evening! 😆 )

**Comment by shawnsquire** [comment]
Thanks!

> However, I'd say it's probably discouraged to even have config caching enabled in a development environment.

This ... is true. To be honest, I couldn't tell you why it was enabled on the system I was testing on. I'll give it a shot when I get a chance.
