### ISSUE TITLE
Ordering fails with Mollie gateway after updating to Beta 4

### ISSUE THREAD

**Issue by ramondrent** [duncanmcclean/simple-commerce#422]
## Description

 

After updating v2.2.21 to v2.3.0-beta.4, ordering with the Mollie checkout fails:

`Call to a member function filter() on array {"exception":"[object] (Error(code: 0): Call to a member function filter() on array at ../vendor/doublethreedigital/simple-commerce/src/Gateways/Builtin/MollieGateway.php:136)`

Status of the order in Mollie dashboard is marked as paid, but with an error: Webhook call failed with status code 500.

## Exact steps to reproduce

1. Use Simple Commerce version 2.2.21
2. Setup Mollie gateway with test credentials
3. Update to version 2.3.0-beta.4 through CP
4. Complete a 'paid' order

## Environment

Statamic 3.1.11 Pro
Laravel 8.40.0
PHP 7.4.15
doublethreedigital/simple-commerce 2.3.0-beta.4
statamic/seo-pro

**Comment by duncanmcclean** [comment]
Will be fixed in next release. e74104d
