### ISSUE TITLE
Different tax rates per product or destination

### ISSUE THREAD

**Issue by jacksleight** [duncanmcclean/simple-commerce#428]
It's sometimes necessary to have products with different tax rates in the same store, for example one site I look after has products at the standard 20% VAT rate, but also a handful of zero VAT rated products. Additionally, it's often necessary to charge different taxes depending on the destination country, and I'm not sure the multi-site features are always going to be the most appropriate solution to that, as you might not want to set up entirely separate sites for each destination you ship to.

## What would you like to see added?

I think the simplest solution to this is to make taxes work in a similar way to shipping. Have a default built-in tax calculator class that functions in the same way as the current fixed tax approach, but allow developers to swap it out for custom classes. Just as an example each class could contain the following methods:

- `calculateTax(Order $order, Product $product)` - Returns the tax amount
- `checkApplicable(Address $address)` - Returns true/false

## Is there a workaround you can use in the meantime?

Not an elegant one. I guess you could set the tax rate to zero so SC doesn't calculate anything, and then just set all you prices to the tax inclusive values, but then you lose accurate tax information in your order data. And I dont think that would work for different taxes depending on destination.

## Would you be open to PR'ing the feature?

I dont think I have enough knowledge of SC internals to do that.

---

If this is something you'd like to see added, please leave a 👍 reaction to this issue.

**Comment by duncanmcclean** [comment]
Good idea!

FYI: If you want to exclude a product from being taxed, you can set `exempt_from_tax: true` on a product entry.

**Comment by duncanmcclean** [comment]
Good news! I'm building a better tax system for Simple Commerce. 🎉  

You'll be able to assign products to tax categories, each tax category can have multiple tax rates (unique for a country/region).

How does that sound?

**Comment by duncanmcclean** [comment]
Closing this issue as it's pretty much do-able in the new system which will come in v2.3 or v3 (haven't decided on next version number yet). However, I'll be sure to update this issue when it's out so you don't miss it!

**Comment by jacksleight** [comment]
> Good news! I'm building a better tax system for Simple Commerce. 🎉
> 
> You'll be able to assign products to tax categories, each tax category can have multiple tax rates (unique for a country/region).
> 
> How does that sound?

Awesome, sounds perfect!

**Comment by duncanmcclean** [comment]
In case you're not already aware (or someone stumbles across this), this exact thing is now possible with the ['Standard Tax Engine'](https://simple-commerce.duncanmcclean.com/tax#content-standard-tax-engine) in Simple Commerce v2.4

**Comment by sstottelaar** [comment]
Is there a way to set the tax rate for an order (or all line items) based on a specific tax zone without relying on the multi-site functionality? For instance, we operate a single shop that serves both Dutch and Belgian customers. When a user selects Belgium as the shipping country, we’d like to apply the Belgian tax zone.

I understand this can be achieved with the multi-site setup, but we’d prefer to keep everything within a single site. Essentially, we want to set the tax rate at the order level rather than at the site level. I hope this explanation is clear!

**Comment by duncanmcclean** [comment]
You don't need to be using multi-site at all - you just need to use the [Standard Tax Engine](https://simple-commerce.duncanmcclean.com/tax#content-standard-tax-engine) and configure two tax zones.

**Comment by sstottelaar** [comment]
Great, that's what we did up to this point. But the question remains is how we change the tax rate on the order. Is it possible to set this programmatically?

**Comment by duncanmcclean** [comment]
> But the question remains is how we change the tax rate on the order. Is it possible to set this programmatically?

Not easily - you'd need to write your own tax engine. I haven't written any docs on it though since I never expected anyone else to need to do it.

Why do you need to programatically set a tax rate, over configuring them in the CP?
