### ISSUE TITLE
Tax calculation is incorrect if result is a round number with no decimals

### ISSUE THREAD

**Issue by jacksleight** [duncanmcclean/simple-commerce#429]
## Description

When calculating a line item's tax amount the calculation is incorrect if the result is a round number with no decimal places. 

## Exact steps to reproduce

* Set `tax.rate` to `20`
* Set `tax.included_in_prices` to `true`
* Create a product costing `26.00` (inclusive of tax)
* The cost of this product exclusive of tax should be `21.666666…`
* The tax amount for this product should be `4.333333…`
* Add to basket with a quantity of `3`
* The line item total (which is exclusive of tax) should be `65.00`, with a tax_total of `13.00`
* Instead the line item total is `77.87`, with a tax_total of `0.13`

## Fix

This appears to be caused by logic in the `Calculator` class that assumes the result from `(string) round($v, 2)`  will always return a numeric string with two decimal places, which it doesn't. Perhaps this is environment specific?

```php
(string) round(13.0, 2) // is "13", not "13.00"
```

This is used here (line 118):

```php
        if ($taxConfiguration['included_in_prices']) {
            $itemTax = str_replace(
                '.',
                '',
                round(
                    $taxAmount,
                    2
                )
            );

            $lineItem['total'] -= $itemTax;
            $data['tax_total'] += $itemTax;
        } else {
            $data['tax_total'] += (int) str_replace(
                '.',
                '',
                round(
                    $taxAmount,
                    2
                )
            );
        }
```

This can be fixed by not using string manipulation and multiplying the value instead:

```php
        if ($taxConfiguration['included_in_prices']) {
            $itemTax = (int) round($taxAmount * 100);

            $lineItem['total'] -= $itemTax;
            $data['tax_total'] += $itemTax;
        } else {
            $data['tax_total'] += (int) round($taxAmount * 100);
        }
```

## Environment

Statamic 3.1.18 Pro
Laravel 8.45.1
PHP 7.4.16
doublethreedigital/simple-commerce 2.3.3

**Comment by duncanmcclean** [comment]
Released in [v2.3.4](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.4)
