### ISSUE TITLE
Support custom request validation in cart item store and cart item update forms

### ISSUE THREAD

**Issue by jacksleight** [duncanmcclean/simple-commerce#432]
## What would you like to see added?

Custom request validation was recently added to the cart update and checkout forms, it would be great if this was also available on the cart item store and cart item update forms, so that custom metadata fields can be validated.

## Is there a workaround you can use in the meantime?

No

## Would you be open to PR'ing the feature?

Yes, but I probably can't look at it straight away.

---

If this is something you'd like to see added, please leave a 👍 reaction to this issue.

**Comment by duncanmcclean** [comment]
d0fdd28d

**Comment by duncanmcclean** [comment]
Released in [v2.3.6](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.6)
