### ISSUE TITLE
Read default values from blueprint when creating a new cart

### ISSUE THREAD

**Issue by jacksleight** [duncanmcclean/simple-commerce#433]
## What would you like to see added?

When a new cart is created it would be useful if it could get it's default values from the blueprint. This would be helpful for things like setting the default country in the shipping and billing addresses, toggles such as Shipping Same as Billing, and any custom fields that may have been added.

This could also allow you to provide things like shipping prices earlier in the process. For example if the majority of your customers are from the same country you could pre-set the delivery country and shipping method, enabling you to display the shipping prices in the basket rather than waiting until later in the checkout process.

## Is there a workaround you can use in the meantime?

It's possible to check for a `null` value when rendering your input elements, and set a default accordingly. This works well for the country fields for example. However toggle fields are not set to `null` initially, they always have a `true/false` value, therefore there is no way to distinguish between an initial value and a value the user has completed.

---

If this is something you'd like to see added, please leave a 👍 reaction to this issue.

**Comment by duncanmcclean** [comment]
Will be included in next version.
