### ISSUE TITLE
Previous purchase required

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#452]
### What would you like to see added?

It'd be nice to require the ability to purchase product B be dependent on the previous purchase of product A. This can be useful, for instance, if offering a product upgrade (e.g., v2.x from v1.x) where the purchase of the upgrade discount "product" (v2.x) requires the previous purchase of the prior version (v1.x)

### Is there a workaround you can use in the meantime?

no

### Priority wise - where's this feature for you?

I'm going to need it at some point in the future but it's not major right now.

**Comment by duncanmcclean** [comment]
Released in [v2.3.21](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.21)
