### ISSUE TITLE
Discount to exclude shipping

### ISSUE THREAD

**Issue by mscruse** [duncanmcclean/simple-commerce#453]
### What would you like to see added?

It would be great if there was a config option to exclude shipping from the discount calculation and only apply the discount to products.

### Is there a workaround you can use in the meantime?

No workaround that I know of.

### Priority wise - where's this feature for you?

I'm going to need it at some point in the future but it's not major right now.

**Comment by duncanmcclean** [comment]
Will be fixed in the next release.

**Comment by duncanmcclean** [comment]
In fact, reopening for now. Had to revert my code as it was causing tests to fail and I couldn't fix them 🙈  I'll try again another day.

**Comment by duncanmcclean** [comment]
Released in [v2.3.21](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.21)
