### ISSUE TITLE
Display inc tax prices in cart

### ISSUE THREAD

**Issue by mscruse** [duncanmcclean/simple-commerce#457]
### Description

In Australia all prices need to be shown inc tax (we call it GST).

On product pages this is all OK. In the cart there is a mixture.

<img width="941" alt="Screen Shot 2021-08-31 at 9 42 27 am" src="https://user-images.githubusercontent.com/22737928/131420069-0ff1578f-82ca-4ce3-a8d6-3ff5606e9453.png">

The above shows the inc tax price in the Price column but in the Total column it shows excluding tax. I need to show total including tax.

This goes for the total of all products - I need to show inc tax. In my SC config the tax rate is set to 10 and true for included_in_prices. 

As shown above we typically show the Tax total also.

Is it possible that each cart line item can have its 3 values and I can choose in the template what to display?

- Product price ex-tax
- Product price inc-tax
- Tax amount

### Environment

Statamic 3.2.1 Solo
Laravel 8.57.0
PHP 8.0.1
doublethreedigital/sc-digital-products 2.2.2
doublethreedigital/simple-commerce 2.3.21

**Comment by mscruse** [comment]
Also related to #458

**Comment by duncanmcclean** [comment]
Don't suppose it works if you set `included_in_prices` to `false`, then re-add the item to your cart?

**Comment by mscruse** [comment]
If I do that in the cart it show the Item Price and Total (based on 1 qty) as $25.00.  Tax as $2.50 which is wrong as the tax component of $25.00 inc tax is $2.27 (correct originally).

Then on the checkout page the total is $27.50.

In my original screenshot the numbers are correct, that is:

- $25.00 is the correct prince including tax
- $22.73 is the correct price excluding tax
- $2.27 is the correct tax amount.

What I need to do is show the inc tax price everywhere - so the Total values should be the inc tax amount.

**Comment by duncanmcclean** [comment]
Hmm, the issue is tax isn't calculated until the product is added to the cart and it could change based on different factors (especially in 2.4 where you can set different rates for different locations).

We do kinda have control over what the Price field returns though (as we do the augmentation via the custom fieldtype). I wonder if it could be done using a custom modifier... 🤔

**Comment by mscruse** [comment]
Ahhh I see. A custom modifier could be good. This issue isn't a showstopper, but would be good to show all pricing inc tax.

**Comment by duncanmcclean** [comment]
Yeah, unfortunately there's not really a way to do that without introducing breaking changes which isn't something I'm up for doing at the moment.

**Comment by duncanmcclean** [comment]
Here's a modifier you can plop into in your `app/Modifiers` folder, call it `IncludingTax.php`. It'll do what you're wanting 😄 

```php
<?php

namespace App\Modifiers;

use DoubleThreeDigital\SimpleCommerce\Facades\Currency;
use Statamic\Facades\Site;
use Statamic\Modifiers\Modifier;

class IncludingTax extends Modifier
{
    /**
     * Modify a value.
     *
     * @param mixed  $value    The value to be modified
     * @param array  $params   Any parameters used in the modifier
     * @param array  $context  Contextual values
     * @return mixed
     */
    public function index($value, $params, $context)
    {
        $taxRate = 20;

        $amount = $value + (($taxRate * $value) / 100);

        return Currency::parse($amount, Site::current());
    }
}
```

You can use it like this in a template, remember to use the `raw` modifier before the including tax one as it'll get the raw amount (eg. `1500`) instead of the formatted amount (eg. £15.00) 

```
{{ price | raw | including_tax }}
```

**Comment by mscruse** [comment]
Brilliant, thanks so much Duncan. Much appreciated.
