### ISSUE TITLE
Coupon tax calculation

### ISSUE THREAD

**Issue by mscruse** [duncanmcclean/simple-commerce#458]
### Description

When using a coupon it is calculated on the ex-tax prince not the inc-tax so the total is incorrect.

SC config has tax rate set to 10 and true for included_in_prices.

In my test I have a coupon created to give a 20% discount.

<img width="375" alt="Screen Shot 2021-08-31 at 9 42 59 am" src="https://user-images.githubusercontent.com/22737928/131420595-1dc6cfc7-e5f0-4a64-92dd-2083ab042a93.png">

20% of a $25 product is $5, making the final total $20 - all inc-tax.

As you can see the coupon discount is $4.54 which is 20% of the ex-tax item price of $22.73.

In the next screenshot - the Checkout page you can see the Grand Total is $20.46 which is the full product price of $25 minus the coupon of $4.54 (calculated on the ex-tax price). Grand total should be $20.

<img width="375" alt="Screen Shot 2021-08-31 at 9 42 59 am" src="https://user-images.githubusercontent.com/22737928/131420773-7934edd3-93b0-406f-92aa-81d219c379b0.png">
 
This is partly related to #

### Environment

Statamic 3.2.1 Solo
Laravel 8.57.0
PHP 8.0.1
doublethreedigital/sc-digital-products 2.2.2
doublethreedigital/simple-commerce 2.3.21

**Comment by duncanmcclean** [comment]
Right - so you want the coupon to be calculated like this? `coupon total = line items total + tax total`

**Comment by mscruse** [comment]
Yeah the coupon discount should be calculated on the inc tax price.

**Comment by duncanmcclean** [comment]
Fixed & tagged in [v2.3.22](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.22)
