### ISSUE TITLE
Leaving Page Warning

### ISSUE THREAD

**Issue by philipboomy** [duncanmcclean/simple-commerce#461]
### Description

Only happens for product collection

When leaving an edit screen for a product despite no changes or after a save I this warning

https://share.getcloudapp.com/Z4ujArn4

### Steps to reproduce

1) Go to edit page of a product /cp/collections/products
2) Try to leave to another place in the CP without changing anything
3) Get warning.

### Environment

Statamic 3.2.2 Pro
Laravel 8.58.0
PHP 7.4.21
doublethreedigital/duplicator 1.3.4
doublethreedigital/simple-commerce 2.3.23

**Comment by duncanmcclean** [comment]
Hmm, this might be a Statamic Core issue instead of a Simple Commerce one - unless it's to do with the Money fieldtype.

**Comment by philipboomy** [comment]
Its not a major thing but Statamic fixed the issue once so was surprised to see it now.

**Comment by duncanmcclean** [comment]
Yeah, I think there's certain fieldtypes that cause it. Are you able to share your product blueprint and I'll give it a test later on?

**Comment by philipboomy** [comment]
I have shared it via Discord as GitHub didnt allow me to upload that file type and I prefer not to copy paste in case of issues with indent.

**Comment by duncanmcclean** [comment]
Thanks! I'll take a look later.

**Comment by duncanmcclean** [comment]
Narrowed it down - seems to be an issue with the 'Product Variants' fieldtype that Simple Commerce provides.

**Comment by duncanmcclean** [comment]
Finally figured this one out - fixed in [v2.3.29](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.3.29)

**Comment by philipboomy** [comment]
Thanks! Appreciate you not giving up on this and fixed it.
