### ISSUE TITLE
PDF receipts have hardcoded company details

### ISSUE THREAD

**Issue by remiduval** [duncanmcclean/simple-commerce#464]
### Description

The PDF receipts received by customers have hardcoded company details (+44 07444 444 4444 -admin@somewhere.com) in `vendor/doublethreedigital/simple-commerce/resources/views/receipt.antlers.html`

I could replace them with my company details directly (ideally with Statamic dynamic values so it can be changed in the CP) but I guess it would be overwritten during the next update? Or is there a way to publish that as a view?

### Environment

Statamic 3.2.2 Pro
Laravel 8.60.0
PHP 8.0.3
4rn0/statamic-v3-image-optimizer 1.0.8
doublethreedigital/simple-commerce 2.3.24
rias/statamic-redirect 1.4.7
roorda-ict/statamic-entries-export 1.0.0

**Comment by duncanmcclean** [comment]
I know, at some point I need to make them dynamic.

For now though, you can publish the view with `php artisan vendor:publish --tag="simple-commerce-views"`. It'll publish to `resources/views/vendor/simple-commerce`

**Comment by remiduval** [comment]
Works for me, thank you!
