### ISSUE TITLE
Form Request causes "access denied"

### ISSUE THREAD

**Issue by philipboomy** [duncanmcclean/simple-commerce#465]
### Description

When using Form Request for validation https://sc-docs.doublethree.digital/v2.3/tags#validation I am getting this error:

_Illuminate\Database\QueryException
SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: YES) (SQL: select count(*) as aggregate from `posts` where `name` = Philip)_ 

### Steps to reproduce

1) Create a form request validation as per https://sc-docs.doublethree.digital/v2.3/tags#validation
2) Go to checkout and on the "information" step have this {{ sc:cart:update request="CheckoutInformationRequest" redirect="/checkout/shippingmethod" }}
3) Submit form and you get the error.

### Environment

Statamic 3.2.2 Pro
Laravel 8.59.0
PHP 7.4.21
doublethreedigital/duplicator 1.3.4
doublethreedigital/simple-commerce 2.3.24

**Comment by duncanmcclean** [comment]
Can you share your validation rules?

**Comment by philipboomy** [comment]
That was embarrassing. I had unique on name which was of course is not possible so I removed that and its working now. The error message just confused me.

**Comment by duncanmcclean** [comment]
No worries!
