### ISSUE TITLE
Order details not save in the backend

### ISSUE THREAD

**Issue by adeelazhar** [duncanmcclean/simple-commerce#925]
### Description

Hello, I'm Adeel Azhar. I'm currently working with the Simple Commerce addon. I've created a checkout page, but when I retrieve the cart ID and update the order, I receive the order ID and shipper details. However, the cart doesn't display the orders in the backend with all the details, and all the shipping fields remain empty without any data stored in the backend.

I've used the following code:

```php
$order = Order::find($_POST["cartid"]);

$userData = [
    'name' => 'John Doe',
    'email' => 'john@example.com',
    'phone' => 'john@example.com',
    'address' => 'john@example.com',
    // Add other user information as needed
];
    
// Set the shipping address
$shippingAddressData = [
    'shipping_name' => 'John',
    'last_name' => 'Doe',
    'shipping_address' => '123 Main Street',
    'address_line2' => 'Apt 4B',
    'shipping_city' => 'Cityville',
    'shipping_postal_code' => '12345',
    'country' => 'US',
    // Add other address information as needed
];

$order->gateway('Credit Card');
$order->paymentStatus('paid');
$order->grandTotal('36999');
$order->data(['shippingAddress' => $shippingAddressData], ['customer' => "test"], ['order_status' => "placed"]);

$order->save();

dd($order);
```

### Steps to reproduce

```php
$order = Order::find($_POST["cartid"]);

$userData = [
    'name' => 'John Doe',
    'email' => 'john@example.com',
    'phone' => 'john@example.com',
    'address' => 'john@example.com',
    // Add other user information as needed
];
    
// Set the shipping address
$shippingAddressData = [
    'shipping_name' => 'John',
    'last_name' => 'Doe',
    'shipping_address' => '123 Main Street',
    'address_line2' => 'Apt 4B',
    'shipping_city' => 'Cityville',
    'shipping_postal_code' => '12345',
    'country' => 'US',
    // Add other address information as needed
];

$order->gateway('Credit Card');
$order->paymentStatus('paid');
$order->grandTotal('36999');
$order->data(['shippingAddress' => $shippingAddressData], ['customer' => "test"], ['order_status' => "placed"]);

$order->save();

dd($order);
```

### Environment

Environment
Application Name: Statamic
Laravel Version: 10.21.1
PHP Version: 8.1.23
Composer Version: 2.4.4
Environment: local
Debug Mode: ENABLED
URL: staging.symptai.com
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: GBP
Gateways: Dummy
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Free Shipping
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 3
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.20.0 PRO

Statamic Addons
aerni/snipcart: 1.0.0
doublethreedigital/simple-commerce: 5.5.0
rias/statamic-redirect: 3.1.0

**Comment by duncanmcclean** [comment]
Out of interest, why are you creating your own checkout form rather than use the [`{{ sc:checkout }}` tag](https://simple-commerce.duncanmcclean.com/tags/checkout) which will handle all of this for you?

**Comment by adeelazhar** [comment]
{{ sc:checkout redirect="/thanks" }}
  {{ if is_paid }}
  <p>Checkout complete!</p>
  {{ else }}
    <input type="text" name="customer[name]" placeholder="Full Name">
    <input type="email" name="customer[email]" placeholder="Email">
 
    <input type="text" name="gift_note" placeholder="Gift Note">
 
    {{ sc:gateways:stripe }}
        
    {{ /sc:gateways:stripe }}
 
    <button type="submit">Checkout</button>
  {{ /if }}
{{ /sc:checkout }}

Also, I've tried using this tag, but it's not saving the data. It's not working for me."

**Comment by duncanmcclean** [comment]
I'd **strongly discourage** building your own Checkout form, please use the built-in functionality.

Have you looked at the Starter Kit for an example of how to use the [`{{ sc:checkout }}` tag](https://github.com/duncanmcclean/sc-starter-kit/blob/main/resources/views/checkout/_cart.antlers.html)?

Also, the majority of the stuff you can do in the `{{ sc:cart:update }}` tag can also be done inside the checkout tag. See the [customer information](https://github.com/duncanmcclean/sc-starter-kit/blob/main/resources/views/checkout/information.antlers.html) template in the starter kit for reference.

The reason your code wasn't saving anything was because you were passing everything as separate arrays and some of the data doesn't belong in `->data()`, your code should look like this:

```php
// Order status shouldn't be updated as part of data
$order->updateOrderStatus(OrderStatus::Placed);

// For customer information, you need to create a Customer first, then add the customer's ID to the order.
$customer = Customer::make()
    ->email('john@example.com')
    ->data([
        'name' => 'John Doe',
    ]);
$customer->save();

$order->customer($customer->id());

// Set data for other fields, make sure the keys match up to keys in your blueprint and save the data in the correct format for the fieldtypes to understand.
$order->data([
    'shipping_address_line1' => '123 Main Street',
    'shipping_country' => 'US',
    // ...
]);
```

**Comment by adeelazhar** [comment]
I've tried using the checkout tag, but nothing seems to work for me. I already have a site, and I've installed the Simple Commerce plugin. Could this be causing the problem?

Additionally, the method $order->updateOrderStatus(OrderStatus::Placed); is also not working for me. It's giving a 'class not found' error.

**Comment by duncanmcclean** [comment]
> I've tried using the checkout tag, but nothing seems to work for me. I already have a site, and I've installed the Simple Commerce plugin. Could this be causing the problem?

What do you mean by "but nothing seems to work for me"?

> Additionally, the method $order->updateOrderStatus(OrderStatus::Placed); is also not working for me. It's giving a 'class not found' error.

You need to import the `OrderStatus` class:

```php
use DoubleThreeDigital\SimpleCommerce\Orders\OrderStatus;
```

**Comment by adeelazhar** [comment]
I used this code:


{{ sc:checkout redirect="/thanks" }}
  {{ if is_paid }}
    <p>Checkout complete!</p>
  {{ else }}
    <input type="text" name="customer[name]" placeholder="Full Name">
    <input type="email" name="customer[email]" placeholder="Email">
    <input type="text" name="gift_note" placeholder="Gift Note">
    <button type="submit">Checkout</button>
  {{ /if }}
{{ /sc:checkout }}

For the checkout, this form opens, but the order details are not saved in the backend.

**Comment by duncanmcclean** [comment]
Are the inputs inside the `{{ sc:checkout }}` form?

**Comment by adeelazhar** [comment]
{{ sc:checkout redirect="/thanks" }}
  {{ if is_paid }}
  <p>Checkout complete!</p>
  {{ else }}
    <input type="text" name="customer[name]" placeholder="Full Name">
    <input type="email" name="customer[email]" placeholder="Email">
 
    <input type="text" name="gift_note" placeholder="Gift Note">
 
   
 
    <button type="submit">Checkout</button>
  {{ /if }}
{{ /sc:checkout }}

Yes, I provided the input fields.

**Comment by adeelazhar** [comment]
But the input fields do not appear in the git message box.

**Comment by adeelazhar** [comment]
That's my site URL: https://staging.symptai.com/
First, visit the shop page: https://staging.symptai.com/shop
Next, proceed to the cart page: https://staging.symptai.com/cart
Then, navigate to the checkout page: https://staging.symptai.com/checkout
Please select the bank payment option and click on 'checkout.'

Once you reach the order processing page where I've implemented the checkout tag {{ sc:checkout }}, you'll notice that the form fields are displayed here.
However, you may also observe that the checkout tag is not functioning properly.

**Comment by duncanmcclean** [comment]
> However, you may also observe that the checkout tag is not functioning properly.

Is this what you mean by "not functioning properly"? 

![image](https://github.com/duncanmcclean/simple-commerce/assets/19637309/c8ff700f-52d7-45a1-afaa-b2f5c2c3145b)

If so, you need to configure email settings in your `.env` or disable email notifications in your `config/simple-commerce.php` file.

**Comment by adeelazhar** [comment]
But it's not showing for me.
Please watch this video: https://www.loom.com/share/19039883d0cb443e9195d4bfdcc9f387?sid=130dcd53-3474-4b0c-9163-ed7b8e54c4b6

**Comment by adeelazhar** [comment]
Sorry for disturbing you again. Now, the checkout is working perfectly fine, but the calculations are not.
![image](https://github.com/duncanmcclean/simple-commerce/assets/18001662/8adbbef4-583d-4b1e-a592-96c430c51cbd)

**Comment by duncanmcclean** [comment]
Is it just the email with the incorrect totals or is it the same in the Control Panel / order markdown files?

**Comment by adeelazhar** [comment]
Everywhere in the order and control panel  the total is not working.

**Comment by adeelazhar** [comment]
![image](https://github.com/duncanmcclean/simple-commerce/assets/18001662/2f9fef99-b029-4e52-9cd4-f17b68df7e54)

**Comment by duncanmcclean** [comment]
Okay. 

Can you share your product's markdown file, your `simple-commerce.php` config and any custom shipping methods you've created?

**Comment by duncanmcclean** [comment]
After some troubleshooting where I wasn't able to reproduce the issue locally, I found that the `vendor/doublethreedigital/simple-commerce/src/Orders/Calculator/LineItemCalculator.php` had been changed so line items weren't being calculated.

See the changed code on the server on the left & the code in Simple Commerce on the right:

![CleanShot 2023-09-29 at 01 09 39](https://github.com/duncanmcclean/simple-commerce/assets/19637309/30531c83-2160-4fff-88a3-2dfc19e26f59)

Please don't edit any files inside the `vendor` directory.
